Declare consts for Validatable
ppy/osu-web pull request #10133
Opened 2023-04-19 12:19 UTC by notbakaneko

Apparently, this is a thing since Traits just copy paste the code into the class. It'll satisfy phpstan since phpstan checks the trait from the context of the class it's used in

2023-04-20 06:31 UTC, nanaya commented
Maybe create an interface with default const instead? That would also remove the need for `method_exists` check in saveOrExplode function and could also add `isValid` check in the base `save` function so the manual override in each models can be removed.

2023-04-27 14:37 UTC, notbakaneko commented
Some classes have variations where `parent::save()` is called separately and having `isValid()` called in the parent doesn't seem to make sense for them; imo, we should also look at making `save()` throw on failing validation instead, considering the number of times `save()` failing as bitten us, especially in tests 🤨

2023-05-08 12:57 UTC, nanaya requested changes

2023-05-08 12:57 UTC, nanaya commented on tests/BroadcastNotificationTest.php
> +            ))
I feel this should be a const array eventually...

(or enum or something)

2023-05-09 08:58 UTC, nanaya approved these changes

2023-05-09 09:20 UTC, merged