Add frontend for legacy api/irc key
ppy/osu-web pull request #10130
Opened 2023-04-19 07:52 UTC by nanaya

The wordings may need some fixing.

Depends on:
- [ ] #10123
- [ ] #10117

2023-04-28 11:50 UTC, notbakaneko requested changes
I've just realized this should be `app_url` not `$field` (and the also maybe the `foreach`?) https://github.com/ppy/osu-web/blob/master/app/Models/ApiKey.php#L67

2023-04-28 11:50 UTC, notbakaneko commented on resources/js/legacy-api-key/controller.ts
> +  private xhrDelete?: JQuery.jqXHR<void>;
needs `@observable`

2023-04-28 11:50 UTC, notbakaneko commented on resources/js/legacy-irc-key/index.tsx
> +    if (!confirm('legacy_irc_key.confirm_new')) return;
```suggestion
    if (!confirm(trans('legacy_irc_key.confirm_new'))) return;
```

2023-04-28 12:00 UTC, notbakaneko requested changes

2023-04-28 12:00 UTC, notbakaneko commented on resources/js/legacy-api-key/form.tsx
> +  readonly onCancelClick = () => {
`readonly`

2023-04-28 12:00 UTC, notbakaneko commented on resources/js/legacy-api-key/details.tsx
> +  private onClickToggleKeyVisibility = () => {
`readonly`

2023-04-28 12:00 UTC, notbakaneko commented on resources/js/legacy-irc-key/controller.ts
> +  createKey() {
also needs `@action` to go with the `@observable` to properly show the spinner or disable button, same for the other create/delete keys

2023-04-28 13:12 UTC, nanaya commented on resources/js/legacy-api-key/form.tsx
> +  readonly onCancelClick = () => {
but it's already readonly 🤔

2023-05-10 13:57 UTC, notbakaneko requested changes
can also do with `attributes` key in model_validation to localise key name
![image](https://github.com/ppy/osu-web/assets/1694544/658e6caf-84ce-4b02-bf2e-849991f89912)

2023-05-11 07:44 UTC, notbakaneko approved these changes

2023-05-11 08:09 UTC, merged