Add support for `Project Loved` type beatmap packs
ppy/osu-web pull request #10159
Opened 2023-05-08 21:39 UTC by Hiviexd

2023-05-09 09:01 UTC, nanaya commented
The two other new categories are still empty and now we're adding another one? 🤨

2023-05-09 14:20 UTC, Hiviexd commented
other categories are out of my control sadly (FA is a pishifat thing and tournaments are a ChillierPear thing). i recently got approval from Ephemeral to do occasional Project Loved medal packs and this PR is related to that. we're currently compiling a list of maps for a pack that will be released in a couple of weeks so this category will certainly get some use.

2023-05-10 12:27 UTC, nanaya requested changes
ping once the packs are ready to be added (or a week ahead or so instead of "couple of weeks")

2023-05-11 08:21 UTC, nanaya approved these changes

2023-05-12 05:04 UTC, merged