Dim forum topic entry if its older than 1 month
ppy/osu-web pull request #10211
Opened 2023-05-19 02:26 UTC by RockRoller01

yay, first real contribution

Colors are placeholder, wasn't quite sure what the colours should be.

Also tried using opacity just like --deleted does, however this didn't feel quite right and wasn't clear enough when a user can see all 3 states:
![image](https://github.com/ppy/osu-web/assets/35633093/85e027f7-5d09-4907-9698-9b68c2c1aa5e)

closes #4017

2023-05-19 05:13 UTC, RockRoller01 commented
Honestly not quite sure how necessary this is, I feel like with the new forums this doesn't do much, might be better to just close the original issue and this PR

2023-05-19 10:58 UTC, Hiviexd commented
honestly i feel like dimming inactive posts would cause confusion among moderators because deleted posts are also dimmed.

i'd suggest following this approach from the [forum figma design library](https://www.figma.com/file/Gz0MIrXMVVdwaKeecOcLlavu/Web%2FForum?type=design&node-id=0-1&t=Qxwa4fpSwOAIbDWe-0) instead:

![image](https://github.com/ppy/osu-web/assets/62819481/8fb70d4d-528e-4145-b12d-2a8c7ba64a85)

2023-05-26 22:13 UTC, RockRoller01 commented
Changed it to be in-line with the figma design, not sure if the level 4 base colours should also be added for the other colours as nothing uses them yet..

2023-06-26 11:07 UTC, nanaya requested changes

2023-06-26 11:07 UTC, nanaya commented on resources/css/bem/forum-topic-entry.less
> +    opacity: 0.5;
I feel this should be at least 0.7 otherwise it's kinda hard to read

2023-07-24 10:16 UTC, nanaya submitted a review, later dismissed

2023-07-24 10:16 UTC, nanaya commented on resources/css/bem/forum-topic-entry.less
> +    --forum-item-background-color: hsl(var(--colour-red-hue), 40%, 30%);
I only meant the `@osu-colour-x` lesscss variable being deprecated, not the whole `--hsl-x`...

2023-07-24 10:16 UTC, nanaya commented on resources/views/forum/forums/_topic.blade.php
> +        {{ class_with_modifiers('forum-topic-entry', $topic->trashed() ? 'deleted' : null, $topic->isOld() ? 'old' : null) }}
```php
['deleted' => $topic->trashed(), 'old' => $topic->isOld()]
```

2023-07-24 10:16 UTC, nanaya commented on app/Models/Forum/Topic.php
> +        if ($this->topic_type !== 0) {
```php
static::TYPES['normal']
```

2023-08-22 05:32 UTC, peppy commented
@nanaya may be worth applying the outstanding review pieces and getting this in if there's nothing else blocking it.

I still think having inactive threads dimmed is beneficial.

2023-09-25 10:39 UTC, notbakaneko approved these changes

2023-09-25 10:50 UTC, merged