fix: Invalid endpoint for v1 in docs
ppy/osu-web pull request #10276
Opened 2023-06-11 18:40 UTC by minisbett

The base url for the v1 api is https://osu.ppy.sh/api/, not https://osu.ppy.sh/api/v1.

I'm not sure what would be the best way to fix this in the docs, tried my best.

2023-06-12 03:04 UTC, peppy commented
A bit confused, You're adding v1 specific documentation to a site which clearly says it's for v2. v1 documentation is found over at https://github.com/ppy/osu-api/wiki

2023-06-12 06:08 UTC, minisbett commented
> A bit confused, You're adding v1 specific documentation to a site which clearly says it's for v2. v1 documentation is found over at https://github.com/ppy/osu-api/wiki

That's a fair point but I guess the endpoint is still incorrect so why not fix it? Or if as you said the V2 docs aren't the place for that remove it completely.

2023-06-13 05:24 UTC, peppy commented
Probably best to remove it. Also maybe the whole version section should be replaced with a link to the changelog (https://osu.ppy.sh/docs/index.html#changelog)

2023-06-15 05:11 UTC, notbakaneko requested changes
Probably should remove `v1` from the docs since we're no longer planning on implementing it on `osu-web`

2023-08-01 13:10 UTC, closed without merging