Convert modding profile posts component to typescript
ppy/osu-web pull request #10278
Opened 2023-06-12 04:41 UTC by notbakaneko

2023-06-16 11:40 UTC, nanaya requested changes

2023-06-21 07:14 UTC, notbakaneko commented on resources/js/modding-profile/posts.tsx
> +              beatmap={null}
It's explicitly selected beatmap or none selected, not optional for the places that use the prop

2023-06-21 07:41 UTC, nanaya commented on resources/js/modding-profile/posts.tsx
> +              beatmap={null}
`null` would mean the post doesn't have beatmap_id (an "all" section post) except it's not always the case here...

2023-06-21 07:59 UTC, notbakaneko commented on resources/js/modding-profile/posts.tsx
> +              beatmap={null}
It's not optional and shouldn't be #10291

2023-06-21 08:43 UTC, nanaya commented on resources/js/modding-profile/posts.tsx
> +              beatmap={null}
with the current usage it ended up being optional but either way it's wrong I guess 🤷

2023-06-22 06:49 UTC, nanaya approved these changes

2023-06-22 07:02 UTC, merged