Remove store address editing
ppy/osu-web pull request #10321
Opened 2023-06-29 08:54 UTC by notbakaneko

No longer supported, handling of physical item shipping has gone via shopify partners for a while now.
Extra validation that forces an error if a non-shopify shippable item tries to checkout.
Placeholders hardcoded for old invoices.

2023-06-30 08:37 UTC, nanaya commented
Should the invoice printing related stuff be removed as well?

2023-06-30 12:17 UTC, notbakaneko commented
printing and shipping-only versions probably don't needed either without shipping being handled on our end 🤔

2023-06-30 15:20 UTC, nanaya approved these changes

2023-06-30 15:20 UTC, nanaya requested changes
I clearly forgot about the comment I made a bit ago

2023-07-03 07:57 UTC, nanaya approved these changes

2023-07-03 08:08 UTC, merged