Convert beatmap discussions history component to typescript
ppy/osu-web pull request #10352
Opened 2023-07-07 10:17 UTC by notbakaneko

Forgot about this one; removed the review context since this is read-only

2023-07-13 12:35 UTC, nanaya requested changes

2023-07-13 12:35 UTC, nanaya commented on resources/js/beatmap-discussions-history/main.tsx
> +                    beatmapset={this.beatmapsets[discussion.beatmapset_id]}
technically this may return null...

2023-07-18 08:13 UTC, nanaya commented on resources/js/beatmap-discussions-history/main.tsx
> +    // - deleted beatmap
is the comment even useful here 🤔

2023-07-18 08:34 UTC, notbakaneko commented on resources/js/beatmap-discussions-history/main.tsx
> +    // - deleted beatmap
I though I removed it 👀

2023-07-18 08:40 UTC, nanaya approved these changes

2023-07-18 08:52 UTC, merged