Remove `doctrine/dbal` and fix migration improper column types
ppy/osu-web pull request #10454
Opened 2023-08-10 23:15 UTC by NiceAesth

Addresses #10453

## Summary

Ever since https://github.com/laravel/framework/pull/45487, Laravel has added support for column modifying which dropped `doctrine/dbal` as a dependency. 

However, if the package is still installed it will continue to use it for type mappings. This caused issues with certain types which the maintainers chose to not map to mysql/mariadb specific types. (e.g. mediumint and int both being mapped to INTEGER, causing migrations between them to effectively do nothing)

## Changes done

- Removed `doctrine/dbal` as a dependency
- Updated migrations to remove previous workarounds caused by dbal
- Changed migrations between `increment()` and `bigIncrement()` since Laravel always sets it as a primary key causing errors such as ```SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined (Connection: mysql, SQL: alter table `osu_scores_high` modify `score_id` bigint unsigned not null auto_increment primary key)```

Note: JSON type and other MySQL types which previously did not have mappings due to dbal maintainers not wishing to support different versions of SQL now have proper mappings in Laravel 10. Additionally, nullable now also specifies default as null with MySQL.

You may see a schema dump obtained from running the new migrations on a fresh database [here](https://gist.github.com/NiceAesth/9f533f2ef7a13a80261860d8b0d8ed37)

2023-08-14 11:49 UTC, nanaya requested changes
It looks like nullable setting isn't preserved on schema change with native migration.

2023-08-14 14:18 UTC, NiceAesth commented
Of note is that all of the `nullable(false)` calls are technically not needed anymore. Did not touch those.

2023-08-15 09:43 UTC, nanaya requested changes
Still missing nullable:
- `changelog_entries.github_user_id` in `database/migrations/2020_05_15_083037_sync_structure.php`
- `contest_entries.user_id` in `database/migrations/2020_05_15_083037_sync_structure.php`

2023-08-16 08:08 UTC, nanaya approved these changes

2023-08-16 08:28 UTC, merged