Move WIP/pending beatmaps to graveyard when approving their beatmapset
ppy/osu-web pull request #10468
Opened 2023-08-15 19:12 UTC by cl8n

rationale in the comment. always feels a little weird to me when i see loved mapsets with wip/pending diffs...

2023-08-22 05:18 UTC, peppy approved these changes
Probably makes sense. Have not tested.

2023-08-24 06:24 UTC, nanaya requested changes

2023-08-24 06:24 UTC, nanaya commented on app/Models/Beatmapset.php
> +        if ($beatmapIds !== null) {
can use a test

2023-09-14 08:35 UTC, nanaya approved these changes

2023-09-14 08:35 UTC, merged