Show rank changes on performance ranking
ppy/osu-web pull request #10597
Opened 2023-09-26 05:38 UTC by cl8n

resolves #7391

---

![](https://github.com/ppy/osu-web/assets/9954349/180d6b1e-291b-4582-a4a4-6f2b3795357d)

2023-09-26 05:38 UTC, cl8n commented
I need some help with caching this per request because currently it gets called 50 times on a ranking page. I don't know the best way to do it
https://github.com/ppy/osu-web/blob/69bc11a2180ac88064087372e7b219b5aab59a25/app/Models/RankHistory.php#L123

2023-09-26 06:25 UTC, nanaya commented
is it normal to have "least recent" ranking to compare against when the others are 30 days? Isn't it usually just `-` to indicate new ranker?

2023-09-26 21:45 UTC, cl8n commented
> is it normal to have "least recent" ranking to compare against when the others are 30 days? Isn't it usually just `-` to indicate new ranker?

yeah I guess this could be misleading in some way. I've changed it so that only the history at exactly 30 days is checked, and everything has an icon of some form now. also further tooltip to explain the "not enough history" case

2024-05-24 13:23 UTC, nanaya requested changes

2024-05-24 13:23 UTC, nanaya commented on resources/css/bem/ranking-page-table.less
> +      pending: @fa-var-ellipsis-h, hsl(0, 0%, var(--c-lightness-1));
`--hsl-f1`? That above is barely any different to just using `#bbb` directly

2024-05-27 12:00 UTC, nanaya approved these changes

2024-05-27 12:08 UTC, merged