Add API endpoints for beatmap packs
ppy/osu-web pull request #10618
Opened 2023-10-05 15:55 UTC by Swekka

Closes #10177
The documentation for the endpoints show up under `Undocumented` and I'm not sure why, I also wasn't sure what to do with `user_completion_data` in the documentation so I've left it empty for now.

2023-10-06 13:43 UTC, notbakaneko commented
> The documentation for the endpoints show up under Undocumented

you have to add a `@group Sectionname` to the phpdoc for the controller

2023-10-12 09:26 UTC, notbakaneko requested changes

2023-10-12 09:26 UTC, notbakaneko commented on app/Http/Controllers/BeatmapPacksController.php
> +        }
api should use `cursor_string` instead of page for pagination, see `EventsController` for an example

2023-10-12 13:34 UTC, notbakaneko requested changes

2023-10-12 13:34 UTC, notbakaneko commented on app/Http/Controllers/BeatmapPacksController.php
> +            $type = presence(get_string($params['type'] ?? null)) ?? BeatmapPack::DEFAULT_TYPE;
this should be moved out of the conditional.

2023-10-12 13:34 UTC, notbakaneko commented on app/Http/Controllers/BeatmapPacksController.php
> +        $packs = BeatmapPack::getPacks($type);
make this the base query for api and non-api requests: 
```
$query = BeatmapPack::getPacks($type);

if (is_api_request()) {
    // do api stuff
    $packs = $query->cursorSort(....);
} else {
    // do non api stuff 
    return ext_view(...., 'packs' => $query->paginate...
}
```
etc

2023-10-12 13:36 UTC, nanaya commented on app/Models/BeatmapPack.php
> +        return Beatmap::modeStr($this->playmode ?? 0);
`null` ruleset_id is not `0`. Also I'd rather not add more api returning ruleset name for now and just return ruleset id instead.

2023-10-13 06:47 UTC, notbakaneko commented on app/Transformers/BeatmapPackTransformer.php
> +            'ruleset_id' => $pack->getRulesetIdAttribute(),
just use `$this->playmode`; also, `getThingAttribute()`s can just be accessed by `->thing`

2023-10-13 09:52 UTC, notbakaneko requested changes

2023-10-13 09:52 UTC, notbakaneko commented on resources/views/docs/_structures/beatmap_pack.md
> +user_completion_data |                             |
`user_completion_data` is just 
```typescript
{
  beatmapset_ids: number[]; // ids of beatmapsets completed by the user (according to the requirements of the pack itself)
  completed: boolean; // whether all beatmapsets completed or not
}
```

2023-10-13 11:52 UTC, notbakaneko approved these changes

2023-10-13 12:08 UTC, merged