Prevent qualified maps with unresolved issues from getting ranked
ppy/osu-web pull request #10675
Opened 2023-10-24 12:46 UTC by notbakaneko

plus an attempt at cleaning up some test methods
closes #10654

- [ ] exclude from ranking queue as well?

2023-10-24 12:49 UTC, nanaya commented
Yeah I think it should be excluded from the queue otherwise potentially fewer maps will be ranked at each runs.

2023-10-26 13:33 UTC, notbakaneko commented
I tried adding tests for hybrid beatmapsets but I'm not sure the results make sense 🤔 
I wonder if these are related  https://github.com/ppy/osu-web/pull/4911/files#diff-4cf8d05043400424e732b329df53d237b69b3d5c10ad285c894aba37cd4835a4R54 
https://github.com/ppy/osu-web/pull/4489/files#diff-03627ef6eb157031bb0c701c8990ea1c6e7713fc129ef82683b5949bb67ebb39R291-R293

2023-10-27 11:26 UTC, nanaya commented
I think the order doesn't matter. By ruleset id:
- 0: anything with 0
- 1: anything with 1 except 0
- 2: anything with 2 except 0 and 1
- 3: anything with 3 and nothing else

2023-10-30 11:13 UTC, notbakaneko commented
nevermind, I'm counting them wrong 👀

2023-11-08 06:34 UTC, nanaya requested changes

2023-11-08 10:10 UTC, notbakaneko commented on app/Console/Commands/ModdingRankCommand.php
> +                    $this->line("{$key}: {$value}");
would have liked to use `twoColumnDetail` but didn't find any option to make the columns narrower 👀

2023-11-09 06:16 UTC, nanaya requested changes

2023-11-09 06:16 UTC, nanaya commented on database/factories/BeatmapsetFactory.php
> +    public function qualified(?Carbon $approvedAt = null)
`\DateTimeInterface`?

2023-11-09 12:37 UTC, nanaya approved these changes

2023-11-09 13:00 UTC, merged