Add column to record playlist item attempts
ppy/osu-web pull request #10686
Opened 2023-10-27 13:13 UTC by nanaya

The table ends up a bit weird with `score_id` changed to nullable but the existing data already partially pointing to either old `multiplayer_scores.id` (which means now pointing to wrong `solo_scores.id`) or just 0 when score link has its own id 🤷

2023-11-01 08:27 UTC, notbakaneko requested changes
Do existing attempts need to be accounted for in the migration?

2023-11-01 09:03 UTC, nanaya commented
it probably should be done after deployment

2023-11-01 13:06 UTC, notbakaneko requested changes

2023-11-02 05:31 UTC, notbakaneko approved these changes

2023-11-22 04:38 UTC, merged