Add some missing translation keys to store
ppy/osu-web pull request #10720
Opened 2023-11-09 16:34 UTC by Swekka

2023-11-09 19:50 UTC, Joehuu commented
It does resolve that issue, yes.

2023-11-09 20:16 UTC, Swekka commented
> #6821 is related to this. Right?

Good catch, I've changed it now

2023-11-10 11:36 UTC, nanaya requested changes

2023-11-10 11:36 UTC, nanaya commented on resources/lang/en/store.php
> +        'shipping_and_handling' => 'Shipping &amp; Handling',
`&` shouldn't be escaped here

2023-11-10 11:36 UTC, nanaya commented on resources/lang/en/store.php
> +                    '_' => "If you didn't request a cancellation please contact :link quoting your order number :order_number.",
order number format is wrong (should be `(#:order_number)`)

2023-11-10 11:54 UTC, nanaya approved these changes

2023-11-10 12:02 UTC, merged