Add video display to artist pages
ppy/osu-web pull request #10765
Opened 2023-11-27 18:33 UTC by venix12

instead of #10761

2023-11-28 10:42 UTC, notbakaneko commented
I'm guessing the video isn't necessarily going to be on youtube only?

2023-11-28 10:44 UTC, venix12 commented
Assumed so considering the newspost ones are hosted on assets.ppy.sh and we are talking the same videos here, @peppy may know better though.

2023-11-28 10:51 UTC, peppy commented
It should always be self hosted on assets.

2023-11-28 11:24 UTC, notbakaneko requested changes

2023-11-28 11:24 UTC, notbakaneko commented on resources/views/artists/show.blade.php
> +                            </div>
If they're always self-hosted then just use `video`; putting video url into iframe also clips the controls on Safari

2023-11-30 12:24 UTC, notbakaneko approved these changes

2023-11-30 12:33 UTC, merged