Store session verification request data in redis
ppy/osu-web pull request #10796
Opened 2023-12-12 13:02 UTC by nanaya

To be used for oauth client verification. The interface will also be implemented on the oauth token later. `Session::instance()` inside "controller" will then be replaced with a helper function which returns either oauth token or (cookies) session accordingly.

2023-12-14 12:13 UTC, notbakaneko requested changes
still checking...

2023-12-14 12:43 UTC, nanaya commented on app/Libraries/SessionVerification/Controller.php
> +class Controller
helpers go to helper. This should only contain http responding methods

2023-12-15 09:28 UTC, notbakaneko commented on app/Http/Controllers/Controller.php
>              UserVerificationState::fromCurrentRequest()->markVerified();
seems to have sneaked back in 🤔

2023-12-15 11:05 UTC, notbakaneko approved these changes

2023-12-15 11:25 UTC, merged