Add oauth verification for password token
ppy/osu-web pull request #10800
Opened 2023-12-13 13:34 UTC by nanaya

```
# reissue verification code
POST api/v2/verify-session/reissue

# verify token
POST api/v2/verify-session
```

On `/me` endpoint response, there's a new attribute `session_verified`.

- [ ] depends on #10796

2023-12-18 12:03 UTC, notbakaneko requested changes
A verified session sending `verification_key` probably should be issuing a new verification code? 🤔

2023-12-18 12:20 UTC, notbakaneko commented on app/Http/Middleware/VerifyUser.php
> +        'users_controller@me' => true,
Also, does this do anything when API requests don't even use this middleware?

2023-12-19 06:39 UTC, notbakaneko requested changes

2023-12-19 06:39 UTC, notbakaneko commented on tests/Controllers/OAuth/TokensControllerTest.php
> +        $meJson = json_decode($meResp->getContent(), true);
There's this `TestResponse::decodeResponseJson()` and `assertPath`/`assertJsonPath` thing

2023-12-19 10:42 UTC, notbakaneko submitted a review, later dismissed
Reminder https://github.com/ppy/osu-notification-server/pull/55 also should be deployed after this is deployed.

2023-12-21 04:00 UTC, peppy commented
> Additionally, notification server will also send verification event when the verification link is opened

Given that we don't yet have any setup for notification server in the game yet, is it fine to ignore this for now? Do we need to poll or something to handle the scenario?

2023-12-21 05:46 UTC, nanaya commented
ignoring it would confuse users. I guess a token status endpoint could be added...

2023-12-21 09:31 UTC, peppy commented
Cancel that, we do have support for notification websocket handling.

But work on this will likely happen early next year from the client side, so let's leave this PR in limbo for now.

2024-01-25 05:59 UTC, nanaya commented
> I would like to get started on this client-side, but I'm not sure I get what fits where exactly, so I'm gonna have a few questions here.
> 
> * From what I can gather, the basic flow is as follows:
>
>
>   Do I have that right?
> 

seems mostly right. The newVerified event is always published regardless of the source. I don't think it matters much in the context of client though.

> * In [this](https://github.com/ppy/osu/pull/25480) comment, the following was stated:
>   > Basically there will be a case where web will let us know via **a response to any API request** that we need verification, which will cause the client to bring up the prompt.
>       
>       
>    Is this really the case here? Do I need to be potentially handling (re-)verification on any response? From source it kinda appears to me that it's only scoped to `GET /api/v2/users/me` but I may well be wrong.
> 

mainly only POST requests will return verification required response (exceptions etc applies). It's the same as web at the moment.

> * Do I need to be handling token _revocation_? As in, if a `UserSessionEvent::newLogout()` event is broadcast, do I need to be doing anything? Is that even something that can happen for a client token right now?

a logout event means the session/token is no longer valid. One case would be when the user changes password (on web) it'll log out all other sessions and tokens.

technically even without handling it any further requests will be denied anyway but at least in osu-web a forced logout will be immediately applied.

2024-01-29 08:26 UTC, peppy approved these changes

2024-01-29 08:26 UTC, merged