Hide global rank display if a score is non-ranked or non-preserved
ppy/osu-web pull request #10988
Opened 2024-02-10 19:04 UTC by tsunyoku

Resolves #10966

2024-02-11 12:13 UTC, cl8n approved these changes
change looks good

...but reviewing design of this page again, i dont think it's great to only show `-` for a case where something isn't included, it kind of prompts the question of "why?" if the user isn't already familiar with how this stuff works

2024-02-14 01:17 UTC, peppy commented
We already have tooltips on the "recent plays" to describe the "why" of this, so it could likely also be done here.

2024-02-16 10:16 UTC, notbakaneko requested changes

2024-02-16 10:16 UTC, notbakaneko commented on resources/js/scores-show/player.tsx
> +          {props.score.rank_global == null || props.score.ranked === false || props.score.preserve === false ? '-' : `#${formatNumber(props.score.rank_global)}`}
Can probably add a tooltip for non-ranked/non-preserved scores like that in `pp-value.tsx` (I think a single generic message should be fine?)
Also, split the line.

2024-02-16 11:35 UTC, notbakaneko requested changes

2024-02-16 11:35 UTC, notbakaneko commented on resources/js/scores-show/player.tsx
> +    title = trans('scores.show.player.no_rank');
`scores.status.no_rank`

2024-02-16 11:37 UTC, tsunyoku commented on resources/js/scores-show/player.tsx
> +    title = trans('scores.show.player.no_rank');
oops

2024-02-16 11:45 UTC, notbakaneko approved these changes

2024-02-16 17:24 UTC, merged