Covert StoreSupporterTag to typescript
ppy/osu-web pull request #11129
Opened 2024-03-29 12:00 UTC by notbakaneko

And react + mobx it

2024-04-01 12:49 UTC, nanaya requested changes

2024-04-01 12:49 UTC, nanaya commented on resources/js/store/store-supporter-tag.tsx
> +        toggleCart(this.isValidUser);
this is triggered too early, causing wrong button state if `target` is specified and the username check takes too long or the user doesn't exist

(irrelevant if not doing any workarounds)

2024-04-01 12:49 UTC, nanaya commented on resources/js/store/store-supporter-tag.tsx
> +        <div className='js-store store-supporter-tag'>
js-store not needed anymore

2024-04-01 12:49 UTC, nanaya commented on resources/js/store/store-supporter-tag.tsx
> +      <>
not needed

2024-04-01 12:49 UTC, nanaya commented on resources/js/register-components.tsx
> +  const maxMessageLength = getInt(container.dataset.maxMessageLength) ?? 0;
weird missing attribute handling with one throwing and one having nonsense default

(and similar to quantity, having product id inside the component just adds complexity compared to just having it directly on plain html)

2024-04-01 12:49 UTC, nanaya commented on resources/js/store/store-supporter-tag.tsx
> +  private readonly giftMessage: string = '';
the attribute name is rather misleading as it's not the actual state...

2024-04-01 12:49 UTC, nanaya commented on resources/js/store/store-supporter-tag.tsx
> +      step: 1,
apparently `sliderValueFrom` isn't needed if `step` is set to something like 0.1? (or 0.125 to copy the current "resolution")

2024-04-02 08:08 UTC, notbakaneko commented on resources/js/store/store-supporter-tag.tsx
> +    }
You'll have to ask @peppy about that 🤷

2024-04-02 10:27 UTC, nanaya approved these changes

2024-04-02 10:27 UTC, nanaya commented
Unrelated but I don't think the slider/button colour is right ಠ_ಠ

2024-04-02 10:35 UTC, merged

2024-04-02 12:14 UTC, notbakaneko commented
The slider is supposed to be pink like the supporter icon 👀