Run remove scores jobs on separate connection
ppy/osu-web pull request #11162
Opened 2024-04-17 08:47 UTC by notbakaneko

Run on separate connection and queue. The issue here is will automatically retry reserved jobs after `retry_after` has expired even it they're still running, so the same job starts being run by multiple workers simultaneously and have their attempt counts incremented, eventually causing `MaxAttemptsExceededException` to be thrown (while the job is still running on the first worker). If the job _does_ fail now, it won't be retried anymore.

There is `WithoutOverlapping` middleware for the job, but that just causes workers trying to run the job while the lock is active to immediate complete the job and release it, completely removing the job from the queues instead of leaving it in the reserved queue.

The reliable solution short of having our own queue runner that makes sense, is for jobs with long timeouts to run on separate workers and queues.

- [ ] another queue worker configured with `artisan queue:work remove_scores --queue=remove_scores --tries=3`

2024-04-25 07:53 UTC, nanaya commented
where did you get that? That's not what the handle function says at least

https://github.com/laravel/framework/blob/ad758500b47964d022addf119600a1b1b0230733/src/Illuminate/Queue/Middleware/WithoutOverlapping.php#L70-L85

`$job->release()` is "Release the job back into the queue after (n) seconds."

2024-04-25 11:13 UTC, notbakaneko commented
oh, it also needs the `InteractsWithQueue` trait added to the job to get the default release behaviour :|

It's still not great:
```
worker 1 dequeues job, increments attempts, acquires lock
retries_after expires
worker 2 dequeues job, increments attempts, fails to lock, places on delayed queue, returns job as done
releaseAfter expires
worker 2 dequeues job, increments attempts...
```
It might be passable but it's also still a roundabout way of having another setting that acts like `retries_after` and doesn't apply the first time; you'd think it should always use the `releaseAfter` value 🤔

2024-04-25 14:00 UTC, nanaya commented
it's probably still better than adding different queue just to have different timeout

2024-04-26 12:07 UTC, nanaya requested changes

2024-04-27 15:04 UTC, nanaya approved these changes

2024-04-27 15:13 UTC, merged