Read & store score total without mods on submission
ppy/osu-web pull request #11211
Opened 2024-05-13 18:06 UTC by bdach

This is being sent from the client after https://github.com/ppy/osu/pull/27912. There's no actual release with that pull out yet, so if you wanna test full-stack, test with latest game `master`.

The intended place of storage is the `data` json. @peppy initially wanted to do a new column for this, but unfortunately due to the fact that columns cannot be added online to `ROW_FORMAT=COMPRESSED` tables, this is not very easy to do on a table with several billion records inside. Thus in the json it goes. It's not guaranteed json will be much better either due to the unpredictable behaviour of json compression, but it seems to be the best way forward.

The param is nullable / allowed-missing for now. It will probably cease to be after submission is disabled for clients that don't send it, and all rows that have it missing are back-populated.

The end goal in sight here is to be able to do perpetual mod multiplier rebalances without precision loss, e.g. https://github.com/ppy/osu/issues/27685. In the future this could also prove useful for something like custom mod multiplier support for tournaments.

2024-05-23 09:33 UTC, bdach commented
> seems working apart of the interface in `solo-score-json.ts` can use an update.

Correct me if I'm wrong but that looks like a frontend-facing interface? I wasn't really intending on exposing this to the frontend at all, it's basically only intended for internal / maintenance usage for when we do need to rebalance mod multipliers.

2024-05-23 09:36 UTC, nanaya commented
yeah but the it kind of documents what attributes the json has

2024-05-23 09:54 UTC, bdach commented
Does https://github.com/ppy/osu-web/pull/11211/commits/1ded710c9554c22a102430807b6e825c60ea9955 work?

2024-05-23 09:55 UTC, nanaya requested changes

2024-05-23 09:55 UTC, nanaya commented on resources/js/interfaces/solo-score-json.ts
> +  total_score_without_mods?: boolean;
yes but why is it a boolean 🤔

2024-05-23 09:58 UTC, bdach commented on resources/js/interfaces/solo-score-json.ts
> +  total_score_without_mods?: boolean;
whoooooooooooooooooops

2024-05-23 12:07 UTC, nanaya approved these changes
kinda wonder about the length of the key though (`total_score_without_mods`)

2024-07-17 09:03 UTC, peppy approved these changes

2024-07-17 09:11 UTC, merged