Support multiple length scales on beatmap filtering
ppy/osu-web pull request #11222
Opened 2024-05-20 21:53 UTC by tsunyoku

Resolves #10938.

Intending to match the length filtering available in the client so added some test cases which are taken from there.

2024-05-23 09:13 UTC, nanaya requested changes

2024-05-23 09:13 UTC, nanaya commented on app/helpers.php
> +        if ($match === 0 || $match === false) {
check for `!== 1` instead?

2024-05-23 09:13 UTC, nanaya commented on app/helpers.php
> +        '/^(?P<seconds>\d+(\.\d+)?)$/',
the `P`s are useless and just adding noise

2024-05-23 09:13 UTC, nanaya commented on app/helpers.php
> +    return ['value' => $time, 'min_scale' => $minScale];
`ComparatorParam` needs an update to handle this change

2024-06-12 13:37 UTC, peppy commented
@tsunyoku ping on this one (requires review application)

2024-06-13 12:46 UTC, merged