Use weighted performance for country leaderboards
ppy/osu-web pull request #11269
Opened 2024-06-13 18:18 UTC by tsunyoku

Resolves #10525.

Added the user count as a config variable just in case it's something that wants to be messed with but seems general consensus from peppy's poll that top 1000 is the best idea.

Unsure if the column on the page should be reworded to say something like "Weighted Performance" so that the difference is clear for those who've looked at the page in the past but it might seem weird since pp leaderboards for example just use "Performance".

Formula for weighted performance is the same as user total performance.

2024-06-14 13:08 UTC, nanaya commented
the formula question is still open. I think the 0.95 factor is too steep for country-sized population. It's effectively 0 after around 300th.

2024-06-14 14:24 UTC, tsunyoku commented
if we want to encapsulate the entire top 1000 then we should use something around 0.99 for the factor, for the 999th user it's ~0.004

2024-06-19 11:49 UTC, nanaya commented
maybe make it configurable for now with 0.99 as the default

2024-06-19 11:49 UTC, nanaya requested changes

2024-06-19 11:49 UTC, nanaya commented on app/Models/CountryStatistics.php
> +            $userPerformances = UserStatistics\Model::getClass(Beatmap::modeStr($modeInt))
missing default user scope

2024-06-20 06:01 UTC, nanaya commented
@peppy please confirm whether or not we want to go on with this

2024-06-20 06:04 UTC, nanaya requested changes

2024-06-20 06:04 UTC, nanaya commented on config/osu.php
> +        'country_performance_user_count' => intval(env('COUNTRY_PERFORMANCE_USER_COUNT', 1000)),
forgot to mention before but the new envs should be added to the `.env.example` file

2024-06-20 06:04 UTC, nanaya commented on app/Models/CountryStatistics.php
> +                })
might as well make a query variable first and use it for both queries. Also the anonymous function can be shortened with `fn ($userQuery) => $userQuery->default()`

2024-06-20 06:27 UTC, peppy commented
@nanaya i'm on board with this change, yes.

2024-06-20 08:51 UTC, nanaya commented
merge conflicts 👀

2024-06-20 09:03 UTC, tsunyoku commented
presumedly from https://github.com/ppy/osu-web/pull/11282, i'll fix

2024-06-20 09:15 UTC, nanaya approved these changes

2024-06-20 09:19 UTC, merged