Remove store processing events and subscribers
ppy/osu-web pull request #11278
Opened 2024-06-18 11:40 UTC by notbakaneko

They're no longer outputting anywhere and the laravel event subscribers didn't have much use for us, so just get rid of all of them and replace with a stat counter / sentry logging.

2024-06-24 01:10 UTC, nanaya requested changes

2024-06-27 23:03 UTC, notbakaneko commented on app/Libraries/Payments/PaymentCompleted.php
> +                );
Actually, no because the `afterCommit` should be running after `order->paid()` so the whole check is just an unneeded leftover now 🤔

2024-06-28 10:29 UTC, notbakaneko commented on app/Libraries/Payments/PaymentProcessor.php
> -            'notification_type' => "{$this->getNotificationType()} ({$this->getNotificationTypeRaw()})",
This was for debugging whereas Sentry has the stack trace and params so it's not needed.

2024-06-28 11:22 UTC, notbakaneko commented on app/Libraries/Payments/PaymentProcessor.php
> +                    'Cancelling order with no existing payment found.',
One is for logging cancels without an existing payment, the other is for the different multiple different types of extra notifications Paypal sends during cancels/chargebacks/disputes, etc

Cancelled payments also don't exist without the original so this condition wouldn't be triggering if there are cancelled payments unless something else has gone wrong.

2024-06-28 11:27 UTC, nanaya commented on app/Libraries/Payments/PaymentProcessor.php
> +                    'Cancelling order with no existing payment found.',
oh so the cancel function actually creates a duplicate entry just with different cancelled value 😐

2024-07-01 10:48 UTC, nanaya approved these changes

2024-07-01 10:54 UTC, merged