Add daily challenge stats
ppy/osu-web pull request #11351
Opened 2024-07-22 11:52 UTC by nanaya

Tried writing tests but it looks kinda horrible and I'm not quite sure if there's better way to do it ಠ_ಠ

depends on
- [x] #11350
- [x] #11343

2024-07-23 11:20 UTC, notbakaneko requested changes
Still checking

2024-07-23 11:20 UTC, notbakaneko commented on app/Models/DailyChallengeUserStats.php
> +        $endTime = $startTime->endOfDay();
unused

2024-07-23 11:20 UTC, notbakaneko commented on resources/css/bem/qtip.less
> +    width: 300px;
`min-width`?

2024-07-23 12:04 UTC, nanaya commented on database/migrations/2024_07_09_074020_create_daily_challenge_user_stats.php
> +            $table->unsignedMediumInteger('playcount')->default(0);
🤷‍♂️

2024-07-23 12:05 UTC, nanaya commented on app/Models/Multiplayer/Room.php
> +    }
maybe after a few years...

2024-07-23 12:18 UTC, nanaya commented on tests/Models/DailyChallengeUserStatsTest.php
> +                'starts_at' => $playTime->startOfDay(),
it reads better and has fewer assumptions

2024-07-23 12:22 UTC, notbakaneko commented
Doing the initial `daily-challenge:user-stats-calculate` and running it again counts as 2 days

2024-07-24 02:52 UTC, notbakaneko approved these changes
Seems to work

2024-07-24 03:01 UTC, merged