Update daily challenge streak count on play instead of at the end of the day
ppy/osu-web pull request #11363
Opened 2024-07-26 13:38 UTC by nanaya

More useful in term of visibility but the percentile stats being updated later may look a bit weird...?

2024-07-28 09:26 UTC, cl8n commented
maybe a note like "Placement counts will update when the challenge ends in x hours" in the popover when you participated today would help w the feeling weird problem

2024-07-29 06:40 UTC, notbakaneko requested changes
I noticed if you `caculate($dateFromWeekBefore)` on already existing stats, it adds to them again and `last_weekly_streak` gets set to the week before 🤔

2024-07-29 07:25 UTC, nanaya commented
Calculating backward isn't really supported and things will break, not just the weekly streak.

2024-07-29 08:19 UTC, notbakaneko approved these changes

2024-07-29 08:19 UTC, merged