Add character limit on contest judging frontend
ppy/osu-web pull request #11410
Opened 2024-08-06 11:45 UTC by notbakaneko

closes #11395

- Also switches to using the same style as chat announcements and artists search page for text boxes
- Use autosizing text area
- streamlining some elements and styling

2024-08-08 11:13 UTC, nanaya commented
this pr is more than just character limit 🤨

2024-08-09 10:15 UTC, nanaya requested changes

2024-08-09 11:36 UTC, notbakaneko commented on resources/js/contest-judge/entry.tsx
> +              ? `${currentScore.value}/${category.max_value}`
I don't know, I didn't make the design 🤷 (there's no design)

2024-08-22 10:40 UTC, nanaya approved these changes

2024-08-22 10:49 UTC, merged