Add platform issue tags
ppy/osu-web pull request #11428
Opened 2024-08-11 22:27 UTC by venix12

This adds buttons for "[osu!lazer]", "[osu!stable]", and "[osu!web]" thread title tagging, as of request of help forum moderators.

Uses separate const from regular tags as it doesn't have icon thing, and is supposed to be visible in thread names in the listing.

Also, genuinely had no idea for icons so they could be better possibly, though a mod-only feature so probably shouldn't matter as much 🤷.

2024-08-12 05:36 UTC, peppy commented
Do these buttons actually fit? Can you provide a screenshot showing how this looks?

Also I don't think we need localisation for any of this.

2024-08-12 09:05 UTC, venix12 commented
Updated the OP with a screenshot. 

As for translations, it's built into issue tags workflow so is easier to just go that way rather than omitting it, it's only tooltips and success messages that get translated anyway, the tag itself doesn't.

2024-08-12 10:30 UTC, peppy commented
is it possible to replace the icons with text? might make it more legible than almost-understandable icons. laz / stb / web maybe.

2024-08-12 22:24 UTC, Hiviexd commented on app/helpers.php
> +        'lazer' => 'laz',
`lzr` feels like a better acronym than `laz`, thoughts?
```suggestion
        'lazer' => 'lzr',
```

2024-08-12 23:58 UTC, cl8n requested changes

2024-08-12 23:58 UTC, cl8n commented on resources/views/forum/topics/_nav.blade.php
>                  @include("forum.topics._issue_tag_{$type}")
or
```blade
@include('forum.topics._issue_tag', ['issueTag' => $type])
```
and no extra blade templates

2024-08-12 23:58 UTC, cl8n commented on app/Models/Forum/Topic.php
> +        }
probably move this logic to its own method cuz it comes up 3 times (`tagForTopicTitle()` or something)

alternatively include the prefix in each PLATFORM_ISSUE_TAGS

2024-08-14 05:33 UTC, nanaya commented
feels like the tags should just be moved to a menu with this amount

2024-08-14 06:04 UTC, peppy commented
I wouldn't be against that.

2024-08-19 16:27 UTC, Blooshing commented
Making a new panel for the buttons would be nice, I wouldn't mind that. Though this design works fine as well since only a few people are using the buttons it really wouldn't matter either way. 

Thanks for the quick work Venix, I appreciate it.

2024-08-22 13:19 UTC, nanaya requested changes

2024-08-22 13:19 UTC, nanaya commented on app/Models/Forum/Topic.php
> +        'lazer',
`str_slug` the type (class name, translation, filename) and use the actual tag string everywhere else instead? The icon helper can just generate the full content (`stb` etc string for the new tags and `<i ...>` for everything else)

2024-08-22 13:19 UTC, nanaya commented on resources/views/forum/topics/_issue_tag.blade.php
> +        @if (in_array($issueTag, $topic::ISSUE_TAGS, true))
view `forum.forums._topic` also needs adjustment

2025-02-01 21:02 UTC, tatitatai commented
I'm still adding the help thread tags manually, just asking because I don't really know github workflow, are we still going to add this at some point? I also would like to ask, is it possible for each icon to have their own color? So that the overview of help forum looks nice too. 
And, why no icons? Can we look for free ones?

By the way, we're currently using these tags:
- question 
- osu!web
- osu!lazer
- osu!stable
- technical support

2025-02-05 15:34 UTC, notbakaneko approved these changes

2025-02-05 15:46 UTC, merged