Refactor username input lookup component
ppy/osu-web pull request #11451
Opened 2024-08-26 08:22 UTC by notbakaneko

To be used by #11377

Combined the `checkUsernameExists` into the new lookup as well.

2024-08-27 03:53 UTC, notbakaneko commented
I wonder if having a `ref` to the component and just getting the value out directly would be better than passing the updated value through a callback 🤔

2024-08-27 11:19 UTC, nanaya requested changes

2024-08-27 11:19 UTC, nanaya commented on resources/js/store/store-supporter-tag.tsx
> +    this.xhr = apiLookup([username]);
the gift link generated in user menu should be `@` prefixed as it was previously strictly username lookup

2024-08-27 11:19 UTC, nanaya commented on resources/js/store/store-supporter-tag.tsx
> +          this.user = userNotFoundJson;
the response isn't an observable so might as well just `response.users[0] ?? userNotFoundJson`?

2024-08-27 12:04 UTC, nanaya commented on resources/js/store/store-supporter-tag.tsx
> +    this.xhr = apiLookup([username]);
or maybe just prefix it before sending the request

2024-08-28 09:33 UTC, nanaya requested changes

2024-08-28 09:33 UTC, nanaya commented on resources/js/components/username-input.tsx
> +  private validUsersContains(userIdOrUsername?: string | null) {
...shouldn't this be `Contain` instead? 🤔

2024-08-30 08:42 UTC, nanaya approved these changes

2024-08-30 08:43 UTC, merged