Add manual refresh to Beatmap Discussions page
ppy/osu-web pull request #11540
Opened 2024-10-09 12:23 UTC by notbakaneko

Auto check for updates with manual refresh for better performance if there are frequent updates (and no posts magically appearing)

Shows a dot if there are updates available
![image](https://github.com/user-attachments/assets/e037fadc-c8b3-4184-ba29-b28b5e13cdcf)

Mobile has the issue where the buttons can overlap the other elements but you can scroll it out of the way:
![image](https://github.com/user-attachments/assets/03f76635-c790-4e84-837d-77757d853257)

2024-10-16 10:50 UTC, nanaya requested changes

2024-10-16 10:50 UTC, nanaya commented on resources/css/bem/floating-toolbar-button.less
> +  @media @mobile {
before modifiers?

2024-10-16 13:31 UTC, notbakaneko commented on resources/js/beatmap-discussions/discussions-state.ts
> +    return moment(this.lastUpdateRaw).unix();
`lastUpdateRaw` is in milliseconds because javascript; doesn't matter, though, this was change to not use `lastUpdate` anyway.

2024-10-17 07:16 UTC, nanaya approved these changes

2024-10-17 07:27 UTC, merged