Add user block management api
ppy/osu-web pull request #11584
Opened 2024-10-22 13:14 UTC by nanaya

That the destroy/store endpoint is returning both friends and blocks feels a bit whack 🤨

Also it means three additional requests just to get full relation lists (friend, block, mapper (once added))...

Related to #10789.

- [x] depends on #11581 for handling the new response

2024-10-29 10:07 UTC, notbakaneko requested changes
I think maybe a separate relations listing and add/remove block/friend returning only the relevant record? 🤔

2024-10-29 10:33 UTC, nanaya commented
but then again for friends list you probably want to fetch the user data as well whereas for blocklist all that's needed is just the id so I'm not sure if combining them is useful

2024-10-31 00:42 UTC, notbakaneko requested changes
Yeah I think it's kind of weird returning both friends and blocks, if anything at all...

I can see the case of knowing that the user is removed from the friends list if blocked, but that can be assumed to be implicit from blocking, so it isn't actually needed. 🤷 
The most I can see is if you're blocking/adding friends from multiple clients open but it would see strange to me if blocking one user in the UI causes the whole list to change. (and I feel like the reason for returning the whole list was 'shove everything into React to render and not think about it' 🤔 )

2024-10-31 08:41 UTC, notbakaneko approved these changes

2024-10-31 09:03 UTC, merged