Add team settings page
ppy/osu-web pull request #11700
Opened 2024-11-29 13:42 UTC by nanaya

The layout is more or less as per design except for image upload area and the buttons (delete button to be added later... maybe). Not much in term of interactivity but at least forms are saved (by the browser and turbo) 😬 May or may not convert to react later if needed.

- [ ] drafting until #11563 is merged

2024-12-04 05:06 UTC, notbakaneko requested changes

2024-12-04 06:59 UTC, nanaya commented on resources/lang/en/teams.php
> +            'application_help' => 'Set to Open to people applying for the team',
oh, I accidentally a word 👀

2024-12-04 07:55 UTC, notbakaneko approved these changes

2024-12-06 06:03 UTC, notbakaneko commented
I thought I merged this already 🤨

2024-12-06 06:14 UTC, merged