Add new API endpoints for forums and topics
ppy/osu-web pull request #11742
Opened 2024-12-13 11:07 UTC by Sheppsu

Closes #7440 

It would be nice to have these available, and in my case, I want to automate some things on my [otdb](https://otdb.sheppsu.me) project by using the api to comb through the tournament forum. I would love to at least have the topic listing endpoint available if not the others.

Adds three endpoints:
- Getting a list of top-level forums and their subforums (2 deep)
- Getting a single forum with extra info like pinned topics
- Getting a sorted list of topics and optionally under a certain forum

2025-02-05 08:05 UTC, nanaya requested changes

2025-02-06 00:45 UTC, Sheppsu commented on app/Http/Controllers/Forum/ForumsController.php
> +                'last_topics' => json_collection($lastTopics, 'Forum/Topic'),
yeah that's true

2025-02-06 08:27 UTC, nanaya requested changes

2025-02-06 08:27 UTC, nanaya commented on app/Http/Controllers/Forum/ForumsController.php
> +                'topics' => json_collection($topics, new TopicTransformer()),
need a `->get()` here (or above, or combined here)

2025-02-06 08:27 UTC, nanaya commented on app/Models/Forum/Topic.php
> +            ['column' => 'topic_last_post_id', 'order' => 'DESC'],
this destroys performance due to no usable index

2025-02-08 00:13 UTC, Sheppsu commented on app/Models/Forum/Topic.php
> +            ['column' => 'topic_last_post_id', 'order' => 'DESC'],
should I just change it to sort by topic time & id?

2025-02-12 06:50 UTC, nanaya commented on app/Models/Forum/Topic.php
> +            ['column' => 'topic_last_post_id', 'order' => 'DESC'],
just remove this and only rely on the post time for now

2025-02-12 23:45 UTC, Sheppsu commented on app/Models/Forum/Topic.php
> +            ['column' => 'topic_last_post_id', 'order' => 'DESC'],
ah I understand now. I misread as meaning both columns didn't have an index

2025-02-13 11:07 UTC, merged