Include user tags in Beatmapset search
ppy/osu-web pull request #11763
Opened 2024-12-25 10:56 UTC by notbakaneko

Needs a new beatmap search index to be built since the tags are being added to the nested beatmap object instead of the top level tags so  that they can be targetted separately.

- [ ] (not really but it's simpler not to reimplement the same function) requires #11750

2025-03-19 03:53 UTC, nanaya requested changes

2025-03-19 03:53 UTC, nanaya commented on app/Libraries/Search/BeatmapsetSearch.php
> +                        'nested' => [
shouldn't this be also shared with the beatmap specific `$nested` query down below?

2025-03-19 03:53 UTC, nanaya commented on app/Jobs/EsDocumentUnique.php
> +    public function __construct($model)
what's this overriding

2025-03-19 03:53 UTC, nanaya commented on app/Libraries/Search/BeatmapsetQueryParser.php
> +                    $option = static::makeTextOption($op, $m['value']);
being able to search for multiple tags would be useful?

2025-03-19 03:53 UTC, nanaya commented on app/Models/Traits/Es/BeatmapsetSearch.php
> +                        ...$beatmapValues,
some fields have different value when in convert mode

2025-03-19 10:13 UTC, notbakaneko commented on app/Libraries/Search/BeatmapsetSearch.php
> +                        'nested' => [
The scoring and matching of the query string is not the same in the other nested filter

2025-03-19 10:21 UTC, nanaya commented on app/Libraries/Search/BeatmapsetSearch.php
> +                        'nested' => [
would this match tag that isn't part of beatmap specific field match? searching by this and difficulty for example

2025-03-19 11:13 UTC, notbakaneko commented on app/Libraries/Search/BeatmapsetSearch.php
> +                        'nested' => [
Searching for `potato foo difficulty=mayday` returns beatmapsets with `mayday` difficulty with relevance score according to how the fields in the query match `potato foo`

2025-03-19 17:38 UTC, notbakaneko commented on app/Libraries/Search/BeatmapsetSearch.php
> +        }
This filter means that specifying multiple tags requires the beatmapset to have a beatmap that has all the tags; having the tags across different beatmaps in the set will not match.

2025-03-24 03:42 UTC, nanaya requested changes

2025-03-24 03:42 UTC, nanaya commented on app/Models/Traits/Es/BeatmapsetSearch.php
> +    private function esBeatmapTags(Beatmap $beatmap): array
can be a static function

2025-03-24 03:42 UTC, nanaya commented on app/Libraries/Search/BeatmapsetSearch.php
> +            $query->filter(QueryHelper::queryString($tag, ['beatmaps.top_tags'], 'and'));
apparently searching for `tag="a b"` will also include beatmaps which has tag `a` and `b` in addition to `a b`...? not sure if intentional.

also `tag="a"` will also include `a b` and I can't find way to filter just `a` (although there isn't such tag at the moment)

2025-03-24 03:42 UTC, nanaya commented on app/Libraries/Search/BeatmapsetSearch.php
> +        }
that'd be weird anyway. just like specifying multiple different difficulty parameters should match beatmap which has all those parameters, not when they're spread across multiple beatmaps within same beatmapset.

2025-03-24 11:57 UTC, notbakaneko commented on app/Libraries/Search/BeatmapsetSearch.php
> +            $query->filter(QueryHelper::queryString($tag, ['beatmaps.top_tags'], 'and'));
Well that's partly a parsing issue unless we want to start going `tag=""a""` for exact matches...
`creator="a"` already includes `a b` and `a c` so it's not really doing anything different at the moment.

2025-03-24 12:49 UTC, nanaya commented on app/Libraries/Search/BeatmapsetSearch.php
> +            $query->filter(QueryHelper::queryString($tag, ['beatmaps.top_tags'], 'and'));
`creator=a` does only include user `a` though 🤔 (it uses user id lookup if the user exists)

2025-03-25 04:27 UTC, nanaya approved these changes
eh, can be adjusted later I guess 🤷‍♀️

2025-03-25 04:39 UTC, merged

2025-03-25 06:22 UTC, notbakaneko commented on app/Libraries/Search/BeatmapsetSearch.php
> +        $tags = Tag::whereIn('name', $this->params->tags)->limit(10)->pluck('name');
so you can't put hundreds of tags in; the limit should be in the parser but I didn't decide whether it should be throwing or how the UI is supposed to handle it

2025-03-25 06:36 UTC, nanaya commented on app/Libraries/Search/BeatmapsetSearch.php
> +        $tags = Tag::whereIn('name', $this->params->tags)->limit(10)->pluck('name');
well, the remaining hundreds of tags will still be looked up anyway... presumably with slower text query instead of keyword