Add warning indicator to review issues that are near existing posts
ppy/osu-web pull request #6481
Opened 2020-08-14 11:27 UTC by nekodex

![Screen Shot 2020-08-14 at 8 22 41 pm](https://user-images.githubusercontent.com/272140/90244547-ef8bb980-de6b-11ea-8d92-0c5b84c3d910.png)

2020-08-20 11:04 UTC, nanaya requested changes

2020-08-20 11:04 UTC, nanaya commented on resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx
> +    const target = event.currentTarget as HTMLElement;
The cast probably isn't needed if the signature has `<HTMLElement>`.

2020-08-24 09:22 UTC, nanaya requested changes

2020-08-24 09:22 UTC, nanaya commented on resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx
> +    if (timestamp == null || !drafts || drafts.length === 0) {
just noticed `!drafts` (should) always return false here.

2020-08-24 09:22 UTC, nanaya commented on resources/assets/lib/beatmap-discussions/editor-discussion-component.tsx
> +              <DraftsContext.Consumer>{this.nearbyIndicator}</DraftsContext.Consumer>
I've mentioned this somewhere else but it looks like storing this to a variable and using it here and in the other place just like `unsavedIndicator` may work and save rendering same thing twice.

2020-08-26 13:22 UTC, nanaya requested changes
Clickable timestamp is probably not the best idea when editing existing post. It's fine(ish) when creating a new one as it's saved to local storage but not quite when editing existing post.

![](https://s.myconan.net/2020-08/msedge_2020-08-26_22-18-10.png)

2020-08-27 11:08 UTC, nekodex commented
Hrm, I suppose those timestamps should really be a (nested?) popup/preview or something to save having to navigate there and back... guess I'll just make them not-links in edit mode for now and figure out a better way later.

2020-08-31 06:46 UTC, nanaya approved these changes

2020-08-31 07:10 UTC, merged