Documentation for Users endpoint related objects
ppy/osu-web pull request #6515
Opened 2020-08-19 12:02 UTC by nanaya

Todo:
- [ ] Beatmapset object
- [ ] Score object
- [ ] Checks and probably add more details

2020-08-26 11:13 UTC, notbakaneko requested changes
I wonder if `supporter` should be changed to `osu!supporter` to match the wiki 🤔

2020-08-26 11:13 UTC, notbakaneko commented on resources/docs/source/includes/_structures.md
> +When a user becomes supporter for the second or more time.
```suggestion
When a user supports osu! for the second time and onwards.
```

2020-08-26 11:13 UTC, notbakaneko commented on resources/docs/source/includes/_structures.md
> +When a user becomes supporter for the first time.
```suggestion
When a user becomes a supporter for the first time.
```

2020-08-26 11:13 UTC, notbakaneko commented on resources/docs/source/includes/_structures.md
> +When a user received supporter tag gift from another user.
```suggestion
When a user if gifted a supporter tag from another user.
```

2020-08-27 13:24 UTC, notbakaneko approved these changes

2020-08-27 13:26 UTC, nanaya commented
wat ಠ_ಠ this thing isn't done yet

2020-09-09 08:31 UTC, notbakaneko approved these changes

2020-09-09 08:52 UTC, merged