Allow only triggering captcha after hitting threshold of failed attempts
ppy/osu-web pull request #6532
Opened 2020-08-21 10:43 UTC by nekodex

Add `RECAPTCHA_THRESHOLD=n` to `.env` to trigger after `n` failed attempts. (if n = 0, it will always show the captcha)

depends on:
- [x] #6526

2020-08-27 09:34 UTC, nanaya requested changes
Conflicts =)

2020-08-27 12:41 UTC, peppy commented
@nanaya is this good to go minus conflicts?

2020-08-27 12:58 UTC, nanaya commented
I haven't tested it

2020-08-31 09:14 UTC, nanaya requested changes

2020-09-02 06:45 UTC, nekodex commented on resources/views/layout/_popup_login.blade.php
> +        function initCaptcha() { captcha.init('{{config('captcha.sitekey')}}', {{captcha_triggered() ? 'true' : 'false'}}); }
Do you have a better idea on how to handle this?

Even if it's updated on logout/whenever, unless we do something like push updates over websocket (overkill?) there's pretty much always going to be edge cases where client-side falls out of sync with the server as to whether or not the captcha should be shown (which is why the `captcha_triggered` return response is a thing...)

The whole point of the captcha is to throttle login attempts, so I feel like an extra required attempt (in certain edge cases) for people with an elevated number of failed logins seems like a fair trade-off?

2020-09-02 06:45 UTC, nekodex commented on app/Http/Controllers/SessionsController.php
> +                    'captcha_triggered' => true,
Do you mean in the wording of the message or something?

2020-09-02 06:46 UTC, nanaya commented on app/Http/Controllers/SessionsController.php
> +                    'captcha_triggered' => true,
As in showing the captcha on the login form

2020-09-02 06:47 UTC, nanaya commented on resources/views/layout/_popup_login.blade.php
> +        function initCaptcha() { captcha.init('{{config('captcha.sitekey')}}', {{captcha_triggered() ? 'true' : 'false'}}); }
the `captcha_triggered` isn't included if it's already triggered server side

2020-09-02 06:49 UTC, nanaya commented on app/Http/Controllers/SessionsController.php
> +                    'captcha_triggered' => true,
Specifically this line here: https://github.com/ppy/osu-web/blob/802d589c964402157549757d78b22997a3a28169/app/Http/Controllers/SessionsController.php#L68

Someone may end up here with front-end still thinking captcha isn't triggered.

2020-09-02 06:59 UTC, nekodex commented on resources/views/layout/_popup_login.blade.php
> +        function initCaptcha() { captcha.init('{{config('captcha.sitekey')}}', {{captcha_triggered() ? 'true' : 'false'}}); }
So... no, and just fix to show again after logout as required?

2020-09-02 07:01 UTC, nanaya commented on resources/views/layout/_popup_login.blade.php
> +        function initCaptcha() { captcha.init('{{config('captcha.sitekey')}}', {{captcha_triggered() ? 'true' : 'false'}}); }
I guess

2020-09-03 07:54 UTC, nanaya approved these changes

2020-09-03 08:04 UTC, merged