More thorough user best score check and cleanup
ppy/osu-web pull request #6561
Opened 2020-08-27 11:09 UTC by notbakaneko

Checks all the user's scores now instead of just the displayed aggregates. Should be computationally cheaper on the elasticsearch side since performing the aggregation requires loading the segment with the scores anyway.

Also changed `searchAfter` to clear the existing search response to the existing search object can be reused at it was intended for cursoring instead of creating a new one.

2020-08-27 11:15 UTC, notbakaneko commented
There's another option where we can just queue all the score ids into the score indexer's queue and it'll do the right thing.

2020-08-31 10:29 UTC, nanaya requested changes

2020-08-31 10:29 UTC, nanaya commented on app/Libraries/UserBestScoresCheck.php
> +        $search = $this->newSearch('osu');
nice mode

2020-08-31 10:52 UTC, nanaya approved these changes

2020-08-31 11:29 UTC, merged