Add model for Staff Log data and LIO endpoints to manage usergroups
ppy/osu-web pull request #6638
Opened 2020-09-13 09:44 UTC by cl8n

start of #6216 🎉 

`POST user-group`, `DELETE user-group`, and `POST user-default-group` correspond to `AddToGroup`, `RemoveFromGroup`, and `SetDefaultGroup` from admin program. all of them take `user_id` and `group_id` params and 404 on model not found. `user-default-group` can also 422 if the user isn't a member of that group first

will add some tests tomorrow

2020-09-15 05:42 UTC, notbakaneko requested changes

2020-09-15 05:42 UTC, notbakaneko commented on app/Http/Controllers/LegacyInterOpController.php
> +        return response(null, 204);
return `$group` and call method directly instead

2020-09-15 06:28 UTC, nanaya requested changes

2020-09-16 00:26 UTC, cl8n commented on app/Models/UserGroupEvent.php
> +    public $timestamps = false;
i didn't see any use for updated_at

2020-09-16 01:15 UTC, cl8n commented on app/Models/User.php
> +    public function addToGroup(Group $group): void
feels more related to User to me since setting default group is related, and that is updating only user attributes

2020-09-16 04:25 UTC, nanaya commented on app/Models/UserGroupEvent.php
> +    public $timestamps = false;
I think you can just set `const UPDATED_AT = null`. And don't use different column name for `created_at`.

2020-09-18 09:33 UTC, nanaya commented on app/Models/User.php
> +    public function addToGroup(Group $group): void
Why is it randomly located in between a bunch of username rename related functions though.

The alternative is to put them in their own library class (in `App\Libraries\User`)

2020-09-28 05:16 UTC, nanaya approved these changes

2020-09-28 07:01 UTC, merged