Faster discussion timeline chart
ppy/osu-web pull request #6658
Opened 2020-09-16 11:47 UTC by nanaya

Simple enough without needing for d3.

2020-09-16 12:15 UTC, peppy commented
do we use d3 elsewhere?

2020-09-16 12:17 UTC, nanaya commented
yeah, charts in profile page, online users at dashboard/landing page, changelog usage, etc.

2020-09-29 08:36 UTC, notbakaneko requested changes

2020-09-29 08:36 UTC, notbakaneko commented on resources/assets/lib/beatmap-discussions/chart.tsx
> +    forOwn(props.discussions, (discussion) => {
I think this can be `for...of Object.values(props.discussions)` instead?

2020-09-30 04:43 UTC, notbakaneko approved these changes

2020-09-30 05:54 UTC, merged