Make backspace and delete behave the same inside of empty nodes (i.e. delete the node)
ppy/osu-web pull request #6667
Opened 2020-09-17 09:08 UTC by nekodex

After Playing around with the scenarios in #6520, I'm thinking it feels best if we only make a change to the delete/backspace behaviour within empty nodes (to remove the current node), but otherwise just leave the other cases as is?

They kinda make sense with how I'd expect delete and backspace to work w.r.t. text before/after the cursor? I'm open to suggestions if anyone has a good argument for if/how they should behave differently.

fixes #6460, fixes #6520

2020-09-24 08:28 UTC, notbakaneko requested changes
Right now, if the current block is not empty, it collapses the next block into it - but if it's empty it does backwards instead which seems confusing, even more so if the blocks are different types.
![out](https://user-images.githubusercontent.com/1694544/94118216-2d76f700-fe88-11ea-8fc5-4f7af371542a.gif)

I think how deleting should behave needs more discussion in general:
https://github.com/ppy/osu-web/issues/6520#issuecomment-698198316

2020-11-06 03:08 UTC, nanaya requested changes
Things explode if you press delete/backspace on empty review. Press clear, select editor, press delete/backspace on that empty post. Console will log bunch of errors and nothing can be typed in.

2020-11-06 03:11 UTC, nanaya commented
Handling pressing delete/backspace on non-empty block can be done in separate PR (once we figure out what to do in those cases).

2020-11-09 05:51 UTC, nanaya requested changes

2020-11-09 05:51 UTC, nanaya commented on resources/assets/lib/beatmap-discussions/editor.tsx
> +      }
this should be done regardless of `editMode` prop as same problem happens when editing reviews

2020-11-12 05:11 UTC, nanaya approved these changes

2020-11-12 06:11 UTC, merged