Add ability to associate user group members with playmode(s)
ppy/osu-web pull request #6747
Opened 2020-10-08 07:31 UTC by nekodex

aka: The ability to mark NAT/BN members as responsible for specific game modes

This is a prerequisite for the nomination changes, as discussed in #6689 and sets up the usergroup/playmode mapping.

Enabling playmode support is done at a per-group level, while the playmodes themselves are defined on the user's membership relation (`phpbb_user_group`) - this means that we can assign playmodes at a per-usergroup-per-user level. e.g. a user can be a NAT for osu! mode but also a BN for osu!+osu!taiko (not sure if this will ever happen, but it's supported)

This PR also has some visible changes:
- playmode(s) are now shown in the user group badge (if enabled for the group and the member has playmodes defined):
![Screen Shot 2020-10-08 at 3 43 13 pm](https://user-images.githubusercontent.com/272140/95424029-00910c80-097d-11eb-864a-c373297b8fcb.png)
- user badges have also been added to user cards (to make group membership more obvious):
![Screen Shot 2020-10-08 at 3 46 02 pm](https://user-images.githubusercontent.com/272140/95424320-6bdade80-097d-11eb-993c-a4c64f90d53b.png)
- ability added to filter the groups page by playmode has been added (if `has_playmodes ` is set for the group):
![Screen Shot 2020-10-08 at 3 57 34 pm](https://user-images.githubusercontent.com/272140/95425282-fff97580-097e-11eb-97a6-eaed06e8d994.png)

---

Things to be aware of before deploying:
- [ ] check if migrations need to be done beforehand manually (mainly concerned about `phpbb_user_group`)
- [ ] the group cache needs to be cleared... somehow (#6554 suggests there's a command, but it didn't work for me in dev, also this will need to be done whenever `has_playmodes` is toggled on a group)
- [ ] will need to construct/run some DB queries to set the relevant playmodes for current NAT/BN/etc members

2020-10-08 12:01 UTC, nekodex commented
marking as blocked because I noticed some edge case issues

2020-10-19 11:26 UTC, nanaya requested changes

2020-10-22 10:35 UTC, nanaya requested changes

2020-10-22 10:35 UTC, nanaya commented on resources/assets/coffee/osu_common.coffee
> +  playmodeToInt: (playmode) ->
not used?

2020-10-22 10:35 UTC, nanaya commented on resources/assets/lib/globals.d.ts
> +  intToPlaymode: (int: number) => string;
doesn't exist?

2020-10-22 10:35 UTC, nanaya commented on app/Models/User.php
> +                if ($group && $group->has_playmodes) {
the first [truthy](https://www.php.net/manual/en/language.types.boolean.php#language.types.boolean.casting) check is rather useless. Similarly the `optional` wrapper below. Additionally there's no need to `clone` if `display_order` is `null`.

2020-10-28 07:37 UTC, nanaya requested changes

2020-10-28 08:04 UTC, nekodex commented on resources/docs/source/includes/_structures/group.md
> +playmodes       | string[] | [GameModes](#gamemode) which the member is responsible for, e.g. in the case of BN/NAT
attribute doesn't exist at all unless it's inside user, which is why I listed it separately... but yeah, also nullable

2020-10-28 08:05 UTC, nanaya commented on resources/docs/source/includes/_structures/group.md
> +playmodes       | string[] | [GameModes](#gamemode) which the member is responsible for, e.g. in the case of BN/NAT
the transformer doesn't imply that though? :thinking:

2020-10-29 08:42 UTC, nanaya approved these changes

2020-10-29 10:10 UTC, nanaya commented
`phpbb_user_group` seems to be only about 500MB so it should be fine even run from migration.

2020-10-29 14:18 UTC, merged

2020-10-29 14:18 UTC, peppy commented
Remaining two steps will happen after deploy.