Add "Remove from Loved" button, event, and notification
ppy/osu-web pull request #6760
Opened 2020-10-14 04:02 UTC by cl8n

resolves #6327

2020-10-14 10:04 UTC, Ephemeralis commented
Does this clear any scores present on the map as well? Currently a specialized command has to be run via legacy web in order to fully reset a Loved map's state correctly, afaik.

2020-10-14 16:42 UTC, cl8n commented
yes

2020-10-16 08:27 UTC, nanaya requested changes

2020-10-16 08:27 UTC, nanaya commented on routes/web.php
> +    Route::put('beatmapsets/{beatmapset}/remove-from-loved', 'BeatmapsetsController@removeFromLoved')->name('beatmapsets.remove-from-loved');
can use same path as `love` with `::delete`

2020-10-20 10:16 UTC, nanaya approved these changes

2020-10-20 10:49 UTC, merged