Allow deleting notifications
ppy/osu-web pull request #6762
Opened 2020-10-14 11:43 UTC by nanaya

Resolves #6621.

Involves adding index to UserNotification so it doesn't take forever to remove orphan Notifications.

```
CREATE INDEX user_notifications_notification_id_index ON user_notifications (notification_id);
```

- [ ] create the index
- [ ] and add `2020_10_14_102730_add_notification_id_index_to_user_notifications` to migrations table

:x: sign to mark notifications read has been changed to :heavy_check_mark: instead (including in the popup). The button wording (and maybe design) could be improved.

Frontend logic for removing notifications is lifted from widget's removal on read system.

![](https://s.myconan.net/2020-10/firefox_2020-10-14_20-34-07.png)

2020-10-19 10:42 UTC, notbakaneko requested changes
should probably add js tests for `NotificationEventDelete`

2020-10-19 10:55 UTC, nanaya commented on app/Models/Notification.php
> +    public static function scrubIdentity(array $identity)
not sure calling it extract as it only makes sure no extra attributes and of correct type :thinking: 

(and extracting identity from `$identity` seems a bit weird)

2020-10-19 11:30 UTC, notbakaneko commented on app/Models/Notification.php
> +    public static function scrubIdentity(array $identity)
it looks more like extracting from raw params since that's being fed in

2020-10-19 11:31 UTC, nanaya commented on app/Models/Notification.php
> +    public static function scrubIdentity(array $identity)
the one that's id based isn't quite just raw params. It's already being extracted somewhere else.

2020-10-20 11:13 UTC, notbakaneko approved these changes

2020-10-29 09:53 UTC, nanaya commented
I'll split off orphan notifications removal so no index change needed for this PR.

2020-11-04 12:40 UTC, notbakaneko commented
If we retain notifications only up to a certain period, do we still need to remove the 'orphan' (also not sure this is the right term since it's technically the parent 🤔 ) notification, since it'll eventually be dropped?

2020-11-05 03:34 UTC, notbakaneko reviewed
Are there any issues for this later if it doesn't remove the dangling notifications now?

2020-11-05 03:37 UTC, peppy commented
We are going to be removing any notifications after a certain period using table partitioning, so should not be an issue.

2020-11-05 03:42 UTC, notbakaneko approved these changes

2020-11-05 09:56 UTC, merged