Allow nominating per gamemode on multi-mode/hybrid beatmapsets
ppy/osu-web pull request #6832
Opened 2020-10-30 09:01 UTC by nekodex

Following on from #6747, this PR allows BN/NAT members to nominate beatmaps per-gamemode (restricted to the modes the member has been assigned)

![Screen Shot 2020-10-30 at 4 54 00 pm](https://user-images.githubusercontent.com/272140/97674259-90376000-1ad0-11eb-953b-1d14a1aca783.png)

The nomination process for non-hybrid beatmaps remains the same and any hybrid beatmaps that already have a nomination on them will use the old requirements (unless the nomination process is restarted, e.g. via disqualification)

resolves #6689

2020-11-12 04:41 UTC, nanaya commented
Conflicts :thinking:

2020-11-13 13:58 UTC, nanaya commented
I meant something more like this where in non-legacy mode, the only difference is in number of nomination requirement :thinking:

Everything else (playmodes parameter, `xNominationCount` format, etc) stay the same regardless whether or not it's hybrid.

https://gist.github.com/nanaya/6205caba5c24fabfd5df51bf5466f8b0

2020-11-24 12:12 UTC, nanaya requested changes

2020-11-27 08:17 UTC, nekodex commented on resources/assets/lib/beatmap-discussions/nominator.tsx
> +                disabled: (this.hybridMode() && this.state.selectedModes.length < 1) || this.state.loading,
i don't think so? this is making sure that the user has selected at least one mode to nominate for in the popup dialog before enabling the submit button

2020-11-30 08:21 UTC, nanaya requested changes

2020-11-30 09:02 UTC, nekodex commented on app/Models/User.php
> +                        // prevent 'full' permission from being overwritten - i.e. if a user is accidentally added to both bng/nat and bng_limited for the same playmode
I'll fix this, but apparently NAT and BNG are mutually exclusive anyway 🤷‍♂️

2020-11-30 09:58 UTC, nanaya approved these changes

2020-11-30 10:19 UTC, merged