Include locale in wiki path
ppy/osu-web pull request #6880
Opened 2020-11-17 12:07 UTC by nanaya

Resolves #6817.

Changes:
- `/help` part is removed because it's a bit too long otherwise
- images now go under its own path (`/wiki/images/`)
- locale is part of the path, after `/wiki`, before page name (`/wiki/en/Welcome`)
- when showing fallback translation, locale in url and selector button shows the requested locale
  - link to english is shown in the menu
- all links to another wiki page inside the page are relative path so going to another page will keep trying requested locale
  - for example if `/wiki/id/Beatmap` doesn't exist, it'll show the page in English but url stays `/wiki/id/Beatmap` and all wiki links inside still point to `/wiki/id/Page_Name`
  - locale menu will show `id` as current locale, and `en` is listed in the menu
- all pages under `Legal/` are always shown under `/legal/<locale>/Page_Name`
  - accessing under `/wiki` will redirect
  - generating such link using `wiki_url` will still generate url under `/legal/`
  - `index` link in header is removed, `Legal` ("listing") page is the top link instead
- sitemap is now under locale path as well `/wiki/<locale>/Sitemap`, complete with locale menu

2020-11-17 12:09 UTC, nanaya commented
Whoever reviewing this should tell me if they want this large PR to be split or not :eyes:

2020-11-25 05:53 UTC, notbakaneko requested changes
Going to something like `/api/v2/wiki/en/images/shared/news/banners/monthly-beatmapping-contest.png`
returns a redirect to... `/wiki/images/images/shared/news/banners/monthly-beatmapping-contest.png`

2020-11-25 05:54 UTC, nanaya commented
I'm not sure if there's any point having images under api endpoint.

2020-11-25 09:02 UTC, notbakaneko commented on app/Http/Controllers/WikiController.php
> +            return ujs_redirect(route('wiki.image', concat_path([$locale === 'images' ? null : $locale, $path])));
Shouldn't this also skip adding the locale to the path for images if it's a valid locale?

2020-11-25 09:57 UTC, notbakaneko approved these changes

2020-11-25 10:08 UTC, merged