Display modding followers count
ppy/osu-web pull request #6955
Opened 2020-12-08 13:53 UTC by venix12

Resolves #6942

based on friends follower count workflow
not really sure if "modding followers" is the best name :thinking:

2020-12-08 15:17 UTC, peppy commented
rather than "modding followers", it should probably just be "x subscribed"

2020-12-08 16:15 UTC, venix12 commented
guess i can just go for "subscribers" instead since the count is already displayed on the button itself

2020-12-09 05:05 UTC, nanaya commented
I'm thinking of renaming "modding" to "mapping" because it's not really about following the user's modding activity.

2020-12-09 07:31 UTC, peppy commented
Yeah, seems weird that it was named Modder in the first place.

2020-12-09 07:34 UTC, venix12 commented
Yes, it would make much more sense, guess it's a thing for another pull request though since it would require changing naming all around the code, including changes from #6909 and #6953 (when merged) which is likely out of scope for this one likely.

2020-12-15 13:18 UTC, venix12 commented
Should be ready for review now, I believe. :eyes:

2020-12-17 06:01 UTC, nanaya requested changes

2020-12-17 07:11 UTC, venix12 commented on resources/lang/en/follows.php
> +        'disabled' => 'subscribers',
https://github.com/ppy/osu-web/blob/866c4b1c45826ecbb100bf516536765910b5b449/resources/lang/en/friends.php#L10-L14

was basing on this, would likely make sense to change though, yes :thinking:

2020-12-17 07:40 UTC, venix12 commented
changed ``subscribers`` to ``mapping subscribers`` as well since it would be less confusing i believe

2020-12-17 08:20 UTC, nanaya requested changes

2020-12-17 08:20 UTC, nanaya commented on resources/assets/lib/follow-user-mapping-button.tsx
> +    if (currentUser.id === this.props.userId && !this.props.alwaysVisible) {
this incorrectly shows the button when `alwaysVisible` is false and user is guest

2020-12-17 08:20 UTC, nanaya commented on resources/assets/lib/follow-user-mapping-button.tsx
> +    const notLoggedIn = currentUser.id == null;
maybe just combine an `||` of these as `canToggle` and use it where needed (always visible check above, title and disabled state below)

2020-12-17 08:20 UTC, nanaya commented on resources/assets/lib/follow-user-mapping-button.tsx
> +    if (currentUserProfile || notLoggedIn) title = osu.trans(`follows.mapping.followers`);
can be done at once with ternary operator `const title = someCheck ? osu.trans(...) : ....`

2020-12-17 09:56 UTC, nanaya approved these changes

2020-12-17 10:08 UTC, merged