Correctly display deleted user
ppy/osu-web pull request #7060
Opened 2021-01-13 07:21 UTC by nanaya

Seems a bit more verbose than it should be :thinking:

2021-01-18 09:22 UTC, notbakaneko requested changes
Does this need to handle the profile page, indexing, groups, etc?

2021-01-18 09:22 UTC, notbakaneko commented on resources/assets/lib/user-card.tsx
> +    if (this.isUserLoaded && !this.user.is_deleted) {
this combination can be made `isUserVisible` property or something, or just have different render for deleted user.

2021-01-18 11:30 UTC, nanaya commented
it should only appear in high scores. Everything else is deleted.

2021-01-19 06:02 UTC, notbakaneko approved these changes

2021-01-19 06:02 UTC, merged