Simpler forum search
ppy/osu-web pull request #7066
Opened 2021-01-14 11:58 UTC by nanaya

Seems working. Full forum reindex is required for title search to work again.

Resolves #7021.

And more. Or less? :thinking: 

- search returns posts instead of topics
- title data is stored in first post
- `users/{user}/posts` uses same search as general forum post

2021-02-15 07:41 UTC, notbakaneko requested changes
`type` looks like it can be removed from the schema since the join isn't used anymore.
It doesn't look like `Topic` needs to be indexed at all?

Also, I'm not sure if allowing searching post text with single character query string is a good idea 🤔

2021-02-15 07:41 UTC, notbakaneko commented on app/Models/Elasticsearch/TopicTrait.php
> +        return ['type' => 'topics'];
the entire thing doesn't seem to be needed anymore.

2021-02-15 07:50 UTC, nanaya commented
type is needed so current index can still be used when the new index is being rebuilt.

> Also, I'm not sure if allowing searching post text with single character query string is a good idea :thinking: 

it's to allow searching user posts without entering query. I suppose I could separate it again but I don't think there's much harm in it?

2021-02-15 09:30 UTC, notbakaneko commented
I think indexing `Topic` and `filter(['term' => ['type' => 'posts']])` can be skipped and `type` not being added to the new schema; we can probably live with the topic title appearing as individual results while the index is rebuilt?

A matching `parent` document doesn't seem to need to exist and the extra field will just be ignored for the new index

2021-02-15 09:40 UTC, nanaya commented
A further cleanup is needed including some logic simplification for indexing and others and I'm thinking of doing them all in followup PR because otherwise this PR would get rather large.

2021-02-15 12:44 UTC, notbakaneko requested changes
this will need to handle missing `topic_title` https://github.com/ppy/osu-web/blob/f69111fe4ab3ad4a839c71472ef89e1e2b78c715/app/Libraries/Elasticsearch/Hit.php#L54

rest seems fine 🤔

2021-02-16 04:25 UTC, notbakaneko approved these changes

2021-02-16 04:25 UTC, merged