Include user statistics for all modes in index
ppy/osu-web pull request #7095
Opened 2021-01-21 10:25 UTC by nanaya

Doing it this way makes it a bit more difficult to have custom includes in the future :thinking: 

Also need to separate `rank` include values as one require additional query while the other doesn't.

Resolves #7038.

2021-01-22 08:00 UTC, nanaya commented on app/Transformers/UserStatisticsTransformer.php
> +            'global_rank' => $stats->globalRank(),
Apparently I used `global_rank` for variants (in this file) and `rank_global` for scores 🤨

2021-02-08 10:18 UTC, notbakaneko requested changes
We should look at standardizing the response fields to either a subtree
```
type: {
  variant1: {},
  variant2: {},
  variant3: {}
}
```
or flat at the top level
```
type_variantX: {}, (or variantX_type?)
```

2021-02-08 10:18 UTC, notbakaneko commented on app/Transformers/UserStatisticsTransformer.php
> +    // TODO: split this into global_rank (already exists) and country_rank
it seems weird to want to split this but then have stats from multiple modes in a `statistics_all` field.

2021-02-08 12:35 UTC, notbakaneko approved these changes

2021-02-08 13:05 UTC, merged