Update php libraries
ppy/osu-web pull request #7119
Opened 2021-01-27 11:18 UTC by nanaya

- [ ] depends on #7108 (or just check this one together)

2021-02-01 13:31 UTC, notbakaneko approved these changes
seems fine so far 🤔

2021-02-01 13:31 UTC, notbakaneko requested changes
or it could conflict 😕

2021-02-02 05:22 UTC, peppy approved these changes

2021-02-02 08:29 UTC, notbakaneko approved these changes

2021-02-02 08:29 UTC, merged