Disable expensive chat presence group by query
ppy/osu-web pull request #7146
Opened 2021-02-01 19:37 UTC by notbakaneko

Breaks the the unread markers on channels; we probably want to try link those with notifications instead or something 🤔

2021-02-02 04:38 UTC, nanaya commented
There's no notification for public channels though. I wonder if it's better to cache the values in channel table instead.

2021-02-02 05:18 UTC, peppy commented
I did notice the inline comment suggesting the last_id should be done client side

https://github.com/ppy/osu-web/blob/dabf703b776ebf225588a55cc962bde2d268f5ef/app/Models/Chat/UserChannel.php#L82-L83

I guess this is referring to doing one initial lookup then tracking from that point onwards client side?

2021-02-02 06:02 UTC, notbakaneko commented
Well, once you start loading messages in the channel, the last id can be inferred, so it's a matter to providing a placeholder until then.

2021-02-02 06:21 UTC, peppy commented
Either way, tracking in the channels table sounds like a valid approach.

2021-02-02 10:46 UTC, nanaya requested changes

2021-02-02 10:46 UTC, nanaya commented on resources/assets/lib/models/chat/channel.ts
> +  get lastMessageId() {
looks like `lastReadId` ended up a bit behind with this as it's only updated before the actual sent message id is set.

2021-02-02 10:48 UTC, nanaya commented
The new column (and migration entry) should also be added ahead of time.

2021-02-02 12:45 UTC, notbakaneko commented on resources/assets/lib/chat/chat-api-responses.ts
> +  last_message_id: number | null;
turns out relying only on client side max id resulting in subtle polling bug 🤔

2021-02-02 13:04 UTC, nanaya submitted a review, later dismissed
Can use one cleanup but otherwise fine if just want to deploy quickly

2021-02-02 13:04 UTC, nanaya commented on resources/assets/lib/chat/chat-worker.ts
> -    const maxMessageId = this.channelStore.maxMessageId;
apparently there's nothing else using `maxMessageId` anymore so it can be removed?

2021-02-02 13:45 UTC, nanaya approved these changes

2021-02-05 02:55 UTC, peppy commented
Column and migration have been added.

2021-02-05 03:00 UTC, peppy approved these changes

2021-02-05 05:12 UTC, merged