Add API documentation to beatmaps routes
ppy/osu-web pull request #7178
Opened 2021-02-06 22:00 UTC by ethamitc

I've added API documentation to the following routes;
- `/api/v2/beatmaps/lookup`
- `/api/v2/beatmaps/{beatmap}`

I was going to do more but I wanted to ensure that I was doing them properly before I continued.

2021-02-08 08:40 UTC, nanaya requested changes

2021-02-08 08:40 UTC, nanaya commented on app/Http/Controllers/API/BeatmapsController.php
> +     * @response "See Beatmap object section.
missing closing quote

2021-02-08 08:40 UTC, nanaya commented on app/Http/Controllers/API/BeatmapsController.php
> +     * beatmapset                           | See [Beatmapset](#beatmapset)
This should mention `ratings` is included. Link to Beatmapset is probably not needed as it's already linked in Beatmap(Compact) section.

2021-02-08 08:40 UTC, nanaya commented on app/Http/Controllers/API/BeatmapsController.php
> +     *  ---
one too many spaces after `*`

2021-02-09 02:54 UTC, nanaya approved these changes

2021-02-09 03:24 UTC, ethamitc commented
Before this PR is merged, is it okay if I go document some more undocumented routes?

2021-02-09 03:38 UTC, peppy commented
Please just open a new pull request.

2021-02-09 03:39 UTC, merged