Add migration for laravel passport 9.x
ppy/osu-web pull request #7215
Opened 2021-02-16 09:13 UTC by notbakaneko

A `provider` column was added; creating a password client from console always tries to set it.
It has no practical use for us, auth code clients still use it as`null`

closes #7214

2021-02-16 09:33 UTC, nanaya requested changes
Maybe add test for creating the token? :thinking:

2021-02-17 11:20 UTC, notbakaneko commented
Looking at it again, not sure how useful adding a test for the token is, we already have tests creating tokens; this seems to be more of an issue with assigning to column that doesn't exist? 🤔

2021-02-17 12:33 UTC, nanaya commented
I mean testing the token creation from the cli using [this](https://laravel.com/docs/6.x/console-tests).

2021-02-22 07:07 UTC, nanaya approved these changes

2021-02-22 07:41 UTC, merged