Open external links in beatmap discussion in new tab
ppy/osu-web pull request #7216
Opened 2021-02-16 09:33 UTC by notbakaneko

closes #7179

link to same discussion -> stays in same tab
link anywhere else -> new tab

2021-02-17 04:09 UTC, nanaya requested changes

2021-02-17 04:09 UTC, nanaya commented on resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
> +      "<a href='#{url}' rel='nofollow' #{attrs ? 'target="_blank"'}>#{linkText ? url}</a>"
should also have `noopener`/`noreferrer` rel for new tab links

2021-02-17 07:07 UTC, notbakaneko commented on resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
> -      "<a href='#{url}' rel='nofollow' #{attrs ? ''}>#{linkText ? url}</a>"
looks like this one is handled by a callback rendering a React, so I'm going to do this one separately 🤔

2021-02-22 08:31 UTC, nanaya requested changes

2021-02-22 08:31 UTC, nanaya commented on resources/assets/coffee/_classes/beatmap-discussion-helper.coffee
> +      osu.link(url, linkText ? displayUrl, options)
`osu.link` accepts unescaped data but strings here are escaped already resulting in double escaping for `&` and others.

2021-03-02 11:11 UTC, nanaya approved these changes

2021-03-02 11:33 UTC, merged