Add `expired` property to multiplayer playlist items
ppy/osu-web pull request #7223
Opened 2021-02-17 08:45 UTC by smoogipoo

I was debating whether to name this `played` or `expired`, but picked `expired` in the end as it could be used for more than multiplayer. For example if a host is ever to be able to "delete" playlist items then we could also set `expired = 1` in that case and preserve scores/etc. Whether such functionality should exist or not is a different question altogether, but I hope the example demonstrates why I didn't want to tie this property down to _just_ the playlist item having been "played" in multiplayer.

2021-02-18 04:06 UTC, nanaya requested changes

2021-02-18 04:06 UTC, nanaya commented on app/Http/Controllers/Multiplayer/Rooms/Playlist/ScoresController.php
> +        abort_if($playlistItem->expired, 422, 'expired playlist item');
This probably should be done in room's (`app/Models/Multiplayer/Room.php`) `assertValidStartPlay`

2021-02-19 03:44 UTC, peppy commented on database/migrations/2021_02_17_073637_add-expired-column-to-playlist-items.php
> +        Schema::table('multiplayer_playlist_items', function (Blueprint $table) {
should be fine to let this run synchronously

2021-02-19 03:44 UTC, peppy approved these changes

2021-02-19 18:50 UTC, nanaya approved these changes

2021-02-20 02:13 UTC, merged