Document API Routes
ppy/osu-web pull request #7246
Opened 2021-02-22 16:08 UTC by ethamitc

I've added documentation for the following API routes;

- `/news`
- `/news/{news}`

Additionally I added the `news` structure.

2021-02-26 13:27 UTC, nanaya requested changes

2021-02-26 13:27 UTC, nanaya commented on app/Http/Controllers/NewsController.php
> +     * Get news posts
title case (also for show)

2021-03-01 00:13 UTC, ethamitc commented on app/Http/Controllers/NewsController.php
> +     * a
I was about to say I'm confused too but I see it now.

2021-03-01 00:14 UTC, ethamitc commented on app/Http/Controllers/NewsController.php
> +     * Renderes the news web page.
I presume it's supposed to return JSON, when will that be fixed?

2021-03-17 04:55 UTC, nanaya commented on app/Http/Controllers/NewsController.php
> +     * Renderes the news web page.
it's been fixed.

2021-03-25 08:52 UTC, peppy commented
@ethamitc are you intending to apply the remaining review to this one?

2021-04-06 17:57 UTC, ethamitc commented
> @ethamitc are you intending to apply the remaining review to this one?

@peppy Yes I am sorry, this current quad for school ends at the end of this week so I've been busy with that.

2021-06-29 11:30 UTC, nanaya commented
Superseded by #7712.

2021-06-29 11:30 UTC, closed without merging