Add unmentioned fields to docs.
ppy/osu-web pull request #7376
Opened 2021-03-25 09:25 UTC by knightss27

Fixes issue #7373.

Should these fields also be defined inside of the ts interface definitions in `/resources/lib`? I mention this as you can see these fields being constructed in the relevant php files, but the ts definitions for both CommentBundleJson and UserJson are missing the fields mentioned here, but I have no clue whether that is purposeful or not.

2021-03-26 04:16 UTC, peppy approved these changes

2021-03-26 04:17 UTC, peppy submitted a review, later dismissed

2021-03-29 05:08 UTC, notbakaneko requested changes

2021-03-29 05:08 UTC, notbakaneko commented on resources/docs/source/includes/_structures/comment_bundle.md
> +cursor            | [Cursor](#cursor)[]                   |
```suggestion
cursor            | [Cursor](#cursor)                     |
```

cursor should just be a `Cursor`

2021-03-29 05:19 UTC, notbakaneko approved these changes

2021-03-29 06:28 UTC, merged