New beatmapset card
ppy/osu-web pull request #7422
Opened 2021-04-05 11:14 UTC by nanaya

Depends on:
- [ ] new audio player attribute #7421
- [ ] updated beatmapset json interface #7420 
- [ ] css-controlled circular progress #7419
- [ ] typescript `formatNumberSuffixed` #7417

[Preview](https://osunext.dev.myconan.net/beatmapsets/)

2021-04-07 10:26 UTC, Phippe commented
I think clicking _anywhere_ on the bottom bar to see the difficulties is more intuitive, at least on mobile:

![image](https://user-images.githubusercontent.com/34287258/113851814-2e280880-979c-11eb-875e-710c6ec87642.jpeg)

2021-04-08 10:20 UTC, notbakaneko commented
conflicts 😔

2021-04-09 09:19 UTC, notbakaneko requested changes
function assignments to class properties should have the semicolon at the end; unfortunately there's no option to turn that off https://github.com/typescript-eslint/typescript-eslint/issues/2633

2021-04-09 09:19 UTC, notbakaneko commented on resources/assets/lib/utils/beatmapset-helper.ts
> +  });
This indent seems fine but eslint is going to complain about it (and the rule itself has many bugs with constructs like this); the easiest way around it seems to be to put the call on the same line like `}).fail` instead.

2021-04-09 09:19 UTC, notbakaneko commented on resources/assets/lib/utils/beatmapset-helper.ts
> +  $.ajax(route('beatmapsets.favourites.store', { beatmapset: beatmapset.id }), {
should be prefixed with `void` to mark the promise as being unhandled apparently https://github.com/typescript-eslint/typescript-eslint/blob/v4.17.0/packages/eslint-plugin/docs/rules/no-floating-promises.md

2021-04-09 12:47 UTC, notbakaneko approved these changes

2021-04-09 12:47 UTC, merged