Add ability to report beatmapsets
ppy/osu-web pull request #7480
Opened 2021-04-13 15:10 UTC by venix12

resolves #7327

![](https://i.imgur.com/GdPHm4F.png)

only unwanted content and beatmap stealing for now (can add more easily), also adds ``BeatmapsetMenu`` component that could be used for other things in the future as well :eyes:

2021-04-14 04:35 UTC, peppy commented
I don't know where the term "Beatmap Stealing" comes from, but that shouldn't be what this report form is used for. That should be handled via a DMCA request exclusively.

2021-04-14 06:11 UTC, venix12 commented
Well, since a long time there are cases of people just taking one's beatmap and submitting it (as-is or slightly modified), it used to be handled by the moderation teams with a proper silence.

2021-04-14 07:02 UTC, peppy commented
Let's not do that any more. It's not the correct process.

2021-06-07 10:51 UTC, notbakaneko requested changes
This looks kind of odd, to be honest
![image](https://user-images.githubusercontent.com/1694544/121003813-e5ef8b80-c7c8-11eb-839f-47e1340633ff.png)

The dots are also just floating there with no feedback at all

2021-06-07 10:51 UTC, notbakaneko commented on resources/assets/lib/beatmapsets-show/beatmapset-menu.tsx
> +                {children}
Separate variable is kind of unnecessary with only a single item with no other significant logic.

2021-06-07 10:51 UTC, notbakaneko commented on resources/assets/coffee/react/beatmapset-page/header.coffee
> +            if currentUser.id?
Also shouldn't show the option to the beatmapset owner.

2021-06-07 21:23 UTC, venix12 commented
what would you suggest instead of those 3 dots, perhaps a button with them inside?

2021-06-08 08:16 UTC, peppy commented
@arflyte can you check on https://github.com/ppy/osu-web/pull/7480#pullrequestreview-677168712 and propose a quick design for this?

2021-06-08 08:18 UTC, arflyte commented
On it. Gimme a moment.

2021-06-08 08:24 UTC, arflyte commented
I think we can use the same design as the fav button but with the exclamation triangle. Something similar can be easily added for the new beatmap info.

2021-06-08 12:44 UTC, venix12 commented
well, according to https://github.com/ppy/osu-web/issues/7327#issuecomment-818384764 it should be hidden under a dropdown menu

2021-06-08 21:58 UTC, notbakaneko commented
I think the idea is that the button shouldn't be prominent and should be more discreet and subdued in appearance like on the use profile page? Thoughts, @arflyte?

2021-07-20 08:42 UTC, peppy commented
@arflyte still waiting for a response from you on this one. as per the previous comments, we don't want this button to be prominent because it is seldom used.

2021-07-20 10:32 UTC, arflyte commented
Missed this. Haven't give this much thought yet, as I was focused on the newer version of the page. We can use the style that we used on the profile page. Keep the ellipsis and put them in a transparent black circle so that it doesn't feel like it's floating. Use the same height as the buttons. Make the circle darker on hover.

2021-08-17 10:47 UTC, notbakaneko requested changes

2021-08-17 10:47 UTC, notbakaneko commented on resources/assets/lib/beatmapsets-show/beatmapset-menu.tsx
> +export const BeatmapsetMenu = (props: Props) => (
`export default function`

2021-08-18 05:42 UTC, notbakaneko approved these changes

2021-08-18 05:57 UTC, merged