Allow changing beatmap difficulty owner
ppy/osu-web pull request #7517
Opened 2021-04-22 07:42 UTC by nanaya

- [ ] The submission server update for handling upload permission will need to be merged in first...

Resolves #2165.

Editing from discussion page

![](https://s.myconan.net/2021-04/firefox_2021-04-22_15-49-28.png)

The dialog itself

![](https://s.myconan.net/2021-04/firefox_2021-04-22_15-51-20.png)

The only indicator of the guest at the moment

![](https://s.myconan.net/2021-04/firefox_2021-04-22_15-49-58.png)

Different badge for post from guest

![](https://s.myconan.net/2021-04/firefox_2021-04-22_15-50-41.png)

Event log (no difference between reset and assignment)

![](https://s.myconan.net/2021-04/firefox_2021-04-22_16-36-31.png)

2021-04-23 05:53 UTC, peppy commented
FWIW the changes from my end are minimal, so it's fine to get this merged in as soon as feasible.

2021-05-10 07:37 UTC, notbakaneko reviewed
Doesn't renaming the migration cause it to try and run again?

2021-05-13 10:34 UTC, notbakaneko requested changes

2021-05-13 10:34 UTC, notbakaneko commented on resources/assets/lib/notification-maps/message.ts
> +  const replacements: Partial<Record<string, string>> = {
should intersect with `{ title: string }` since title should always be present.

2021-05-13 10:34 UTC, notbakaneko commented on resources/assets/lib/notification-maps/message.ts
> +    replacements.beatmap = item.details.version;
`NotificationDetails` interface needs to be updated

2021-05-13 10:34 UTC, notbakaneko commented on resources/assets/lib/notification-maps/url.ts
> +      return route('beatmapsets.discussion', { beatmapset: item.objectId, beatmap: item.details.betamapId });
key order

2021-05-13 10:39 UTC, notbakaneko commented
Also, there's now this situation on mobile
![image](https://user-images.githubusercontent.com/1694544/118114653-d88dee00-b422-11eb-9979-ac95cc615ca8.png)

2021-05-13 12:42 UTC, notbakaneko approved these changes

2021-05-13 12:56 UTC, merged