Include channel in response when joining channel
ppy/osu-web pull request #7522
Opened 2021-04-23 12:24 UTC by notbakaneko

Some initial updates before adding UI support for joining/rejoining public and multiplayer channels on web.

2021-04-23 12:25 UTC, notbakaneko commented on app/Http/Controllers/Chat/ChannelsController.php
> +            $channel->addUser($sender);
I'm not sure this is necessary since `Room` includes the `channel_id` so you can use the other endpoint instead 🤔

2021-04-28 02:01 UTC, nanaya requested changes

2021-04-28 02:01 UTC, nanaya commented on app/Http/Controllers/Chat/ChannelsController.php
> +            $room = Room::findOrFail($params['target_id']);
what's the conclusion on joining multiplayer room?

2021-04-28 05:20 UTC, notbakaneko commented
This need a bit of rework 🙃

2021-05-19 06:26 UTC, nanaya commented
conflicts

2021-05-19 07:26 UTC, nanaya requested changes

2021-05-19 07:26 UTC, nanaya commented on resources/assets/lib/chat/conversation-list.tsx
> +  @computed
are the `@computed` actually useful considering all the functions do is simply returning another `@computed` value?

2021-05-19 07:26 UTC, nanaya commented on resources/assets/lib/chat/conversation-list.tsx
> +    return <div key='separator' className='chat-conversation-list-separator' />;
key not needed

2021-05-19 07:26 UTC, nanaya commented on resources/assets/lib/chat/conversation-list.tsx
> +    return this.pmChannels.map((conversation) => <ConversationListItem key={conversation.channelId} channelId={conversation.channelId} />);
the actual functions seem rather same so `renderChannel` instead and map from main `render` function?

2021-05-19 08:09 UTC, nanaya approved these changes

2021-05-19 08:36 UTC, merged