Mask negative notification count
ppy/osu-web pull request #7575
Opened 2021-05-10 07:25 UTC by notbakaneko

closes #7324

2021-05-10 08:25 UTC, nanaya reviewed
Should the `chat-icon` component be updated as well? (why are they even two separate almost same component)

2021-05-10 08:28 UTC, nanaya commented
The original issue is even on chat-icon component whoops :eyes:

2021-05-10 08:30 UTC, notbakaneko commented
🤔

2021-05-14 05:38 UTC, nanaya requested changes

2021-05-14 05:38 UTC, nanaya commented on resources/assets/lib/register-components.coffee
> +reactTurbolinks.registerPersistent 'notification-icon', MainNotificationIcon, true, (el) ->
the html element class name should probably match the component name

2021-05-14 05:38 UTC, nanaya commented on resources/assets/lib/notification-icon.tsx
> +        <i className='fas fa-comment-alt' />
icon should differ between main and chat

2021-05-14 05:38 UTC, nanaya commented on resources/assets/lib/notification-icon.tsx
>      if (core.notificationsWorker.hasData) {
I wonder if this should be moved to the chat/main themselves and make this component non-observer

or the other way where the parent component just passing relevant function and this component observes all the changes...

2021-05-18 04:18 UTC, nanaya approved these changes

2021-05-18 04:46 UTC, merged