Improve featured artist beatmaps visibility
ppy/osu-web pull request #7609
Opened 2021-05-16 12:54 UTC by venix12

Resolves #3777 

- adds ``featured_artist`` and ``artist_id`` fields to ``osu_beatmapsets``, both need to be set for map to have the featured artist badge displayed
- adds a golden featured artist search filter
![](https://i.imgur.com/MRRBDGH.png)
- adds featured artist badge on beatmapset panel and listing (silimar to explicit one), one on beatmapset page points to the artist page
![](https://i.imgur.com/E79hNZI.png)
![](https://i.imgur.com/o4kF8sB.png)
- adds link to beatmapsets of featured artist on artist's page
![](https://i.imgur.com/1XFf678.png)

to-do:
- [ ] run ``php artisan es:index-documents --types=beatmapsets --yes``
- [ ] possibly some admin page to attach featured artist to beatmapset or can be added to database staright?

2021-05-18 20:54 UTC, pishifat commented
some songs are available on multiple artist listings, so it'd be good to allow assigning multiple artist ids to a single song

2021-05-19 02:23 UTC, peppy commented
If that's going to be a common thing, sounds like something we should fix at the other end (and reference the `track_id` rather than the artist).

2021-05-19 08:50 UTC, Nivalyx commented
> 
> 
> If that's going to be a common thing, sounds like something we should fix at the other end (and reference the `track_id` rather than the artist).

ah, the occurence is not that common actually but cases like these -do- happen from time to time yeah. here are all the maps that fell into such scenario iirc :

- Culprate & Dictate - Pencilina [(1)](https://osu.ppy.sh/beatmapsets/755651#osu/1590460) [(2)](https://osu.ppy.sh/beatmapsets/722634#osu/1564457), from both Culprate and Dictate's FA catalogue
- Culprate & Joe Ford - Gaucho [(1)](https://osu.ppy.sh/beatmapsets/847776#osu/1772923) [(2)](https://osu.ppy.sh/beatmapsets/937645#taiko/1960216) [(3)](https://osu.ppy.sh/beatmapsets/936234#taiko/1963887), from both Culprate and Joe Ford's FA catalogue
- DJ'TEKINA//SOMETHING - Hidamari no Uta [(1)](https://osu.ppy.sh/beatmapsets/831322#osu/1741594) [(2)](https://osu.ppy.sh/beatmapsets/966324#osu/2022692), from both MOtOLOiD and Yuyoyuppe's FA catalogue
- ginkiha - Winter Night Highway [(1)](https://osu.ppy.sh/beatmapsets/998565#taiko/2090565), from both Rising Sun Traxx and ginkiha's FA catalogue
- Panda Eyes & Teminite - Highscore [(1)](https://osu.ppy.sh/beatmapsets/615326#fruits/1297908) [(2)](https://osu.ppy.sh/beatmapsets/332532#osu/736214), from both Rising Sun Traxx and ginkiha's FA catalogue
- Panda Eyes & Teminite - Immortal Flame (feat. Anna Yvette) [(1)](https://osu.ppy.sh/beatmapsets/720024#osu/1520231) [(2)](https://osu.ppy.sh/beatmapsets/703957#osu/1511760), from both Rising Sun Traxx and ginkiha's FA catalogue
- Shawn Wasabi + YDG feat. YUNG GEMMY - Burnt Rice (Aiobahn & Jh-Anu Remix) [(1)](https://osu.ppy.sh/beatmapsets/519256#osu/1103732), from both Shawn Wasabi and Aiobahn's FA catalogue
- Yuyoyuppe - Emerald Galaxy [(1)](https://osu.ppy.sh/beatmapsets/682286#osu/1442757), from both MOtOLOiD and Yuyoyuppe's FA catalogue

aside from that to my knowledge there are also some other tracks that, although not yet mapped, are also featured in two or more FA pages (such as Powerless feat. Sennzai - Todestrieb for example) so yeah referencing the `track_id` intstead might be the best thing to do going forward here ;~;

2021-05-19 09:24 UTC, cl8n commented
associating by track is the more specific relation so I also think that's the way to go. that's technically a many-to-many bc some maps compile multiple songs together

2021-05-19 10:21 UTC, venix12 commented
``track_id`` solution seems to make sense, where should the badge point then? to artist if there is one and just display "featured artists" with no url for ones assigned to multiple ones? or perhaps some more tricky solution 🤔

2021-05-24 00:40 UTC, venix12 commented
@peppy Tracks in the current infrastructure can belong to only one artist so having it as ``track_id`` wouldn't change much at the very moment. Correct me if I'm wrong but I see two possible solutions of this problem:
- creating a pivot table with that would allow a track to be assigned to multiple artists
- creating a pivot table which would allow multiple artists to be assigned to a single beatmapset

Which one would you go with?

2021-07-14 05:03 UTC, nanaya commented
Add the `track_id` to beatmapsets table for now. We'll figure out how to deal with tracks with multiple artists later. Similarly for the link, link to the referenced track's artist.

2021-08-06 14:48 UTC, Nivalyx commented
*i'm not clayton but...*

...@nanaya as of now (limiting the scope to the Ranked/Loved beatmaps only) iirc there are 15 beatmaps that fall into such case -- the 14 that i mentioned earlier in [this reply](http://github.com/ppy/osu-web/pull/7609#issuecomment-843891837) + [Andromedik - Invasion](http://osu.ppy.sh/s/789544) which is now featured in both [High Tea Music](http://osu.ppy.sh/beatmaps/artists/26)'s and [Andromedik](http://osu.ppy.sh/beatmaps/artists/177)'s Featured Artist listing

this is in addition to a few more that will be so in the near future once certain Featured Artists are announced (that i know of)

2021-08-10 05:17 UTC, peppy commented
Just to reiterate, `track_id` at a beatmapset level is the best approach for now. We can make this system more complex if/when required, but let's get the basics out for now.

2021-08-30 00:27 UTC, venix12 commented
Yeah, changed to the ``track_id``, should be pretty much ready for review now i guess :eyes:

Also, should there be an admin panel thingy added for that or is it going to be set on the database level? (@peppy)

2021-08-30 00:38 UTC, peppy commented
> Yeah, changed to the `track_id`, should be pretty much ready for review now i guess 👀
> 
> Also, should there be an admin panel thingy added for that or is it going to be set on the database level? (@peppy)

fine without for now

2021-08-30 09:05 UTC, nanaya requested changes
Without interface on osu-web, whoever updating the beatmapset table will need to also queue reindex job for the updated beatmapsets...

2021-08-31 18:00 UTC, venix12 commented
> Without interface on osu-web, whoever updating the beatmapset table will need to also queue reindex job for the updated beatmapsets...

so should it be added or not? or in another pr perhaps?

2021-08-31 18:05 UTC, peppy commented
For now it's fine to assume it will be handled elsewhere, until we have a process setup for that. It's out of scope for this PR.

2021-09-01 08:19 UTC, nanaya requested changes

2021-09-01 08:19 UTC, nanaya commented on resources/assets/lib/beatmapset-panel.tsx
> +          {(this.props.beatmapset.track !== null) && <FeaturedArtistBadge />}
this check doesn't work because `!== null` is false when `track === undefined` (unless there's specific reason, `!= null` is generally preferred)

2021-09-01 08:22 UTC, nanaya commented on resources/assets/lib/beatmapset-panel.tsx
> +          {(this.props.beatmapset.track !== null) && <FeaturedArtistBadge />}
actually, this won't even work without `track` being included. Use `track_id` instead

2021-09-01 23:47 UTC, venix12 commented on resources/assets/coffee/react/beatmapset-page/header.coffee
> +                href: laroute.route 'tracks.show', @props.beatmapset.track_id
i see, should i keep the include and the interface for future usage (?) or should it be just removed? 🤔

2021-09-02 08:30 UTC, nanaya commented on resources/assets/coffee/react/beatmapset-page/header.coffee
> +                href: laroute.route 'tracks.show', @props.beatmapset.track_id
remove it for now

2021-09-03 08:02 UTC, nanaya approved these changes

2021-09-03 08:06 UTC, nanaya commented
@peppy beatmapsets table need updating but may want to check if should be done through a different method because it may take a while (adding column and index; see the checklist in the first post)

2021-09-03 08:17 UTC, peppy commented
Not sure it needs to be a BIGINT, that's optimistic for sure.

2021-09-03 08:21 UTC, peppy requested changes

2021-09-03 08:21 UTC, peppy commented on database/migrations/2021_08_30_153214_add_track_id_to_beatmapsets.php
> +            $table->bigInteger('track_id')->unsigned()->nullable();
let's change to `INT` to match the `artist_tracks` table.

2021-09-03 08:22 UTC, nanaya commented
hm yeah, that could be changed as needed

2021-09-03 08:27 UTC, peppy commented
Migration has been applied

2021-09-03 09:39 UTC, nanaya approved these changes

2021-09-03 09:54 UTC, merged