Misc. markdown library improvements
ppy/osu-web pull request #7631
Opened 2021-05-20 12:10 UTC by cl8n

resolves #7586 + some renaming

2021-05-24 11:52 UTC, nanaya requested changes
apparently I remembered it wrong and the larger api change happens in 2.0 which isn't released yet :eyes:

2021-05-24 11:52 UTC, nanaya commented on app/Libraries/Markdown/Osu/Extension.php
> +            ->addBlockRenderer(Table::class, new Renderers\TableRenderer())
now they're registered too late and not actually used

2021-05-24 12:32 UTC, cl8n commented on app/Libraries/Markdown/OsuMarkdown.php
> +        $this->indexableConverter = new MarkdownConverter($indexableEnvironment);
by "the other way as well" u mean the main converter and processor?

2021-05-24 12:33 UTC, nanaya commented on app/Libraries/Markdown/OsuMarkdown.php
> +        $this->indexableConverter = new MarkdownConverter($indexableEnvironment);
yes

2021-05-24 12:36 UTC, cl8n commented on app/Libraries/Markdown/OsuMarkdown.php
> +        $environment->addExtension(new Osu\Extension($this->processor));
some of the processor's info is used to set OsuMarkdown attributes in `process()`, I wasn't sure how to better communicate those from inside the extension

2021-05-24 12:41 UTC, nanaya commented on app/Libraries/Markdown/OsuMarkdown.php
> +        $environment->addExtension(new Osu\Extension($this->processor));
the extension is just a class...

2021-05-25 10:54 UTC, cl8n commented on app/Libraries/Markdown/OsuMarkdown.php
> +        $environment->addExtension(new Osu\Extension($this->processor));
... so now OsuMarkdown holds a reference to the extension instead of processor? I don't see much of a difference 🤔

2021-05-25 10:59 UTC, nanaya commented on app/Libraries/Markdown/OsuMarkdown.php
> +        $environment->addExtension(new Osu\Extension($this->processor));
one passes environment twice, one doesn't

2021-05-27 06:54 UTC, nanaya approved these changes

2021-05-27 07:09 UTC, merged