Include is_restricted in User API responses
ppy/osu-web pull request #7651
Opened 2021-05-26 00:10 UTC by cl8n

and update docs. resolves #7526

2021-06-04 04:15 UTC, nanaya commented
Conflicts

2021-06-07 12:09 UTC, notbakaneko requested changes
`is_restricted` should only be present on `/api/v2/me` or on the user the token is for.

2021-06-09 04:04 UTC, cl8n commented
I wasn't sure whether to make the API inconsistent with included fields like that or not, but alright.

also had trouble deciding if another `OsuAuthorize` check for transformer was the right way to do this...

2021-06-11 08:36 UTC, notbakaneko requested changes

2021-06-11 08:36 UTC, notbakaneko commented on app/Libraries/OsuAuthorize.php
> +        if ($user !== null && $user->user_id === $owner->user_id) {
prefer using `getKey()` when possible.

2021-06-14 10:52 UTC, notbakaneko approved these changes

2021-06-14 11:05 UTC, merged