Fix stripped query and hash for wiki images
ppy/osu-web pull request #7677
Opened 2021-06-02 00:25 UTC by cl8n

they are sometimes used to avoid hitting an old media cache, but I think it also just feels more expected that a URL you write on wiki will stay intact when it makes its way to web.

2021-06-04 10:15 UTC, nanaya requested changes

2021-06-09 04:14 UTC, cl8n commented on app/Libraries/Markdown/Osu/DocumentProcessor.php
> +                $locale = $this->wikiLocale ?? config('app.fallback_locale');
reverted moving to here, almost same thing

2021-06-09 04:34 UTC, nanaya commented on app/Libraries/Markdown/Osu/DocumentProcessor.php
> +                $locale = $this->wikiLocale ?? config('app.fallback_locale');
well, except that one is quite a bit weird takes more lines

2021-06-09 09:24 UTC, nanaya approved these changes

2021-06-09 09:38 UTC, merged