Document news API endpoints
ppy/osu-web pull request #7712
Opened 2021-06-10 06:31 UTC by cl8n

supersedes #7246 , my mistake that I didn't see it before starting work on this, but it does seem abandoned and incomplete anyway.

also removes the now unused `public` scope from these routes

2021-06-10 06:32 UTC, cl8n commented on app/Http/Controllers/NewsController.php
> +     * </aside>
this is a lot to make sense of for a one-sentence notice but idk how else to word it 🤔

2021-06-15 04:52 UTC, nanaya requested changes

2021-06-15 04:52 UTC, nanaya commented on app/Http/Controllers/NewsController.php
> +     * @urlParam news string News post slug or ID. Example: 2021-04-28-new-featured-artist-emilles-moonlight-serenade
missing `required`

2021-06-15 04:52 UTC, nanaya commented on app/Http/Controllers/NewsController.php
> +     * Returns a [NewsPost](#newspost) with `content` and `navigation` included. Querying by ID will return a redirect to query by slug.
The redirect should probably be skipped for api request instead to match user api behavior

2021-06-15 04:52 UTC, nanaya commented on resources/views/docs/_structures/news_post.md
> +title        | string                  | |
sort (also for others)

2021-06-15 04:52 UTC, nanaya commented on resources/views/docs/_structures/news_post.md
> +slug         | string                  | Unique identifier made by joining the publish date and title.
The relation to publish date and title isn't actually in the code. It's just the filename used in github

2021-06-21 10:36 UTC, nanaya approved these changes

2021-06-21 10:50 UTC, merged