Return UserRelation instead of UserCompact for friends API
ppy/osu-web pull request #7768
Opened 2021-06-21 08:37 UTC by cl8n

resolves #7637

2021-06-21 09:05 UTC, nanaya commented
It looks like this will need to be coordinated with lazer.

2021-06-21 21:03 UTC, cl8n commented
yep. I'll wait for review on this first to get the API decided

I also removed the `statistics` include from the users in this response because I don't think it made sense to use the auth'd user's default mode (`friends.read` doesn't imply knowledge of that)... but lazer does use that info currently. should I add it back and require `identify` scope too or something?

2021-06-23 06:52 UTC, peppy commented
Fine to go ahead with this at your discretion (assuming this seems like a sane change - I think it does but haven't looked into it with too much thought).

Will coordinate the lazer side changes if/when this is merged.

2021-06-28 13:24 UTC, nanaya requested changes

2021-06-28 13:24 UTC, nanaya commented on app/Http/Controllers/FriendsController.php
> +                    ->withMutual()
Make its own relation and load that instead.

```php
// in User model
public function relationFriends()
{
  return $this->relations()->friends()->withMutual();
}

// in this controller action
// the loaded reloaded data will be used regardless (in json for api, in current user default json for html)
$relations = $currentUser->relationFriends;
$relations->load(['target' => fn ($q) => $q->...]);

if (is_api...) {
    ...
}

$user = $relations->pluck('target');

// in Transformers etc
$user->relationFriends

2021-07-20 08:35 UTC, peppy commented
@cl8n still willing to apply the review to this one?

2024-10-24 08:35 UTC, nanaya commented
The main thing has been merged through a different PR. Feel free to open another PR for the documentation (or maybe wait for the documentation system update PR (#11433) first?).

2024-10-24 08:35 UTC, closed without merging