Document changelog API endpoints and structures
ppy/osu-web pull request #7774
Opened 2021-06-22 20:42 UTC by cl8n

2021-06-24 08:27 UTC, nanaya requested changes

2021-06-25 02:41 UTC, cl8n commented on app/Http/Controllers/ChangelogController.php
> +     * A [Build](#build) with `changelog_entries`, `changelog_entries.github_user`, and `versions` included.
for the code it's like this bc the other route requires a valid `UpdateStream`, which apparently not all `Build`s have

2021-06-25 05:21 UTC, nanaya commented on app/Http/Controllers/ChangelogController.php
> +     * A [Build](#build) with `changelog_entries`, `changelog_entries.github_user`, and `versions` included.
by same function I mean the function which generates json itself.

also the `default()` scope already checks for valid updatestream.

2021-06-30 11:15 UTC, nanaya approved these changes

2021-06-30 11:29 UTC, merged