Add Overall Difficulty (OD) query in beatmapset search
ppy/osu-web pull request #7799
Opened 2021-06-26 17:48 UTC by gagahpangeran

closes #7783

2021-06-27 18:15 UTC, peppy submitted a review, later dismissed
Looks sane

2021-06-28 04:19 UTC, nanaya requested changes

2021-06-28 04:19 UTC, nanaya commented on app/Libraries/Search/BeatmapsetSearch.php
> +            'od' => ['field' => 'beatmaps.diff_overall', 'type' => 'range'],
the key used here should match the one used in transformer (`accuracy`)

2021-06-28 04:19 UTC, nanaya commented on app/Libraries/Search/BeatmapsetSearchParams.php
> +    public $od;
use native type declaration for new codes

2021-06-28 04:19 UTC, nanaya commented on app/Libraries/Search/BeatmapsetSearchRequestParams.php
> +            'od' => 'od',
similarly here should map to match the attribute in transformer (although looking again, the normalization should've been done in query parser instead)

2021-06-28 10:23 UTC, nanaya approved these changes

2021-06-28 10:35 UTC, merged