Include poll data in forum topic JSON
ppy/osu-web pull request #7814
Opened 2021-06-30 09:40 UTC by cl8n

resolves #7439

also tried factory class per #7788. added more stuff to legacy Topic factory though, bc I didn't want to change a bunch of unrelated tests, and it's pretty easy to port to class later.

2021-07-06 12:02 UTC, nanaya requested changes

2021-11-01 08:29 UTC, nanaya requested changes

2021-11-01 08:29 UTC, nanaya commented on app/Libraries/OsuAuthorize.php
> +        if ($topic->posts()->withTrashed()->first()->poster_id === $user->getKey()) {
This part isn't reachable using oauth but this doesn't use preloaded `firstPost` (and maybe just use `topic_poster` instead)

2021-11-05 08:39 UTC, cl8n commented on app/Transformers/Forum/PollTransformer.php
> +    public function includeTotalVoteCount(Topic $topic): ResourceInterface
how do u decide `transform` vs default include?
I think I originally made this an include because it loads polloptions

2021-11-05 08:44 UTC, nanaya commented on app/Transformers/Forum/PollTransformer.php
> +    public function includeTotalVoteCount(Topic $topic): ResourceInterface
it's in defaultIncludes and just a primitive value so there's nothing about this needs to be an include

2022-02-15 09:27 UTC, nanaya approved these changes

2022-02-15 09:54 UTC, merged