Consolidate logout js
ppy/osu-web pull request #7820
Opened 2021-07-01 10:04 UTC by notbakaneko

Less places to look for logout handlers

2021-07-01 12:45 UTC, nanaya commented on resources/views/layout/_popup_user.blade.php
> +        data-method="delete
🤔

2021-07-01 12:49 UTC, notbakaneko commented on resources/views/layout/_popup_user.blade.php
> +        data-method="delete
🤔

2021-07-02 05:05 UTC, nanaya requested changes

2021-07-02 05:05 UTC, nanaya commented on resources/assets/lib/user-login-observer.ts
> -  userLogout = () => {
`isNotificationEventLogoutJson` notification event handler in SocketWorker needs an update as well

2021-07-05 08:34 UTC, nanaya approved these changes

2021-07-05 08:49 UTC, merged