Add more tests for osu-common
ppy/osu-web pull request #7913
Opened 2021-07-23 09:10 UTC by gagahpangeran

Not testing all functions yet, but at least add more coverage.

2021-07-28 13:16 UTC, notbakaneko requested changes
A lot of the test naming is redundant; `describe` does not need `test ` in front of everything.
Considering the its methods being tested directly, they are probably better described with `describe('.methodName')`.

`it('...')` preferably should be describing what is happening instead of just repeating the expected return value, where possible.

2021-07-28 13:16 UTC, notbakaneko commented on tests/karma/osu_common.spec.ts
> +    it('should return true for existed translation', () => {
`returns true when the translation exists`

2021-07-28 13:16 UTC, notbakaneko commented on tests/karma/osu_common.spec.ts
> +    it('should return false for non existed translation', () => {
`returns false when the translation does not exist`

2021-07-28 13:16 UTC, notbakaneko commented on tests/karma/osu_common.spec.ts
> +    it('should return correct value in KB', () => {
`correct` is a bit redundant seeing as it should be expected already...

2021-07-28 13:16 UTC, notbakaneko commented on tests/karma/osu_common.spec.ts
> +    it('shoudl return integer number', () => {
`should return the number as an integer` or better describing the test, `formats the number without precision`

2021-08-03 08:38 UTC, gagahpangeran commented on tests/karma/osu_common.spec.ts
> +  })
The linter settings (both tslint and eslint) does not include test folder, so my formatter does not auto format this files(?) ¯\\_ (ツ)_/¯

And lint script in CI also does not include test folder, so I'm not aware of this.

2021-08-05 08:39 UTC, notbakaneko approved these changes
some descriptions can be fixed later

2021-08-05 08:56 UTC, merged