Refactor chat presence response
ppy/osu-web pull request #8014
Opened 2021-08-16 13:39 UTC by notbakaneko

Now just uses `ChannelTransformer`.
Some additional moderator checks should be fixed now as well.

preloaded users stored in `request()->attributes` for now; this should be moved to a container object if this kind of lookup is useful for other stuff.

2021-08-24 12:43 UTC, nanaya requested changes

2021-08-24 12:43 UTC, nanaya commented on app/Models/Chat/Channel.php
> +        $userChannel->setRelation('user', $user);
this can be done as part of `userChannelFor`?

2021-08-24 12:43 UTC, nanaya commented on app/Models/Chat/Channel.php
> +        $this->userChannel = $userChannel;
store in an array keyed by user id? Can then also be set by the getter function

2021-08-24 12:43 UTC, nanaya commented on app/Models/Chat/Channel.php
> +        if ($userChannel->user_id !== $user->getKey()) {
probably not going to make much sense but can use check of `channel_id`

2021-08-24 12:43 UTC, nanaya commented on app/Http/Controllers/ChatController.php
> +                'can_message' => $channel?->canMessage($user) ?? false,
haven't checked but this seem to be always false for new channels? (`?sendto=user` where there's no pm channel with the `user` yet)

2021-08-24 12:48 UTC, notbakaneko commented on app/Transformers/Chat/ChannelTransformer.php
> +    }
I was wonder whether it'd be better to change the whole response format to `UserChannel[]` instead 👀

2021-08-24 12:52 UTC, nanaya commented on app/Transformers/Chat/ChannelTransformer.php
> +    }
An alternative is `current_user_attributes` like currently in BeatmapDiscussion and BeatmapsetCompact :thinking:

2021-08-31 12:05 UTC, nanaya requested changes

2021-09-01 11:56 UTC, nanaya approved these changes

2021-09-01 12:20 UTC, merged