Add websocket chat support
ppy/osu-web pull request #8121
Opened 2021-09-15 14:12 UTC by notbakaneko

Replaces polling for messages and channel presence with broadcasting messages via websockets.

This initial version uses the existing notification server to relay messages to the web clients.

2021-09-28 09:51 UTC, nanaya commented
Merge conflicts

2021-10-04 11:22 UTC, nanaya requested changes
not quite done checking :eyes:

2021-10-04 11:22 UTC, nanaya commented on app/Events/ChatMessageEvent.php
> +class ChatMessageEvent implements ShouldBroadcastNow
at over half second for 10k users this may not quite be good to be run synchronously as part of the request...

2021-10-14 11:49 UTC, nanaya commented
Merge conflict...

2021-11-04 11:45 UTC, nanaya requested changes

2021-11-12 11:24 UTC, notbakaneko commented on app/Transformers/Chat/MessageTransformer.php
> +        'uuid',
it's not useful for normal listings, though

2021-11-12 11:29 UTC, nanaya commented on app/Transformers/Chat/MessageTransformer.php
> +        'uuid',
only set if set? :thinking:

2021-11-19 13:24 UTC, nanaya requested changes

2021-11-19 13:24 UTC, nanaya commented on resources/assets/lib/stores/channel-store.ts
> +      void channel.loadEarlierMessages();
looks like can be inlined with some `?.`

2021-11-22 11:26 UTC, notbakaneko commented on resources/assets/lib/stores/channel-store.ts
> +        const channelId = parseInt(key, 10);
`groupBy` types the key as `string`

2021-11-22 12:49 UTC, nanaya commented on resources/assets/lib/stores/channel-store.ts
> +        const channelId = parseInt(key, 10);
or more like object keys are all string because js object isn't proper map =[

2021-11-24 10:12 UTC, nanaya approved these changes

2021-11-24 10:27 UTC, merged