Better handling of cancelled payment callbacks
ppy/osu-web pull request #8140
Opened 2021-09-21 12:46 UTC by notbakaneko

- paypal can send multiple callbacks that get treated as a cancellation
- also replaced status strings with constants (and labelled to closer reflect their state) since finding the actual matching relevant strings is quite annoying :|

2021-09-30 08:01 UTC, nanaya requested changes

2021-10-01 13:17 UTC, notbakaneko commented on app/Models/Store/Order.php
> +        return in_array($this->status, [static::STATUS_CHECKOUT_STARTED, static::STATUS_PAYMENT_APPROVED], true);
A user approving or authorizing a payment doesn't cause the payment to complete; the fun of payment capture gateways.

2021-10-01 13:29 UTC, nanaya commented on app/Models/Store/Order.php
> +        return in_array($this->status, [static::STATUS_CHECKOUT_STARTED, static::STATUS_PAYMENT_APPROVED], true);
the name is confusing regardless... :neutral_face: 

Either `STATUS_PAYMENT_WAITING_CONFIRMATION` (or `STATUS_CHECKOUT_COMPLETED`) const or `isAwaitingPaymentConfirmation` function name or something along that line?

2021-10-05 13:28 UTC, nanaya approved these changes

2021-10-05 13:44 UTC, merged