Remove underline in beatmap discussion history thumbnail
ppy/osu-web pull request #8169
Opened 2021-10-01 09:33 UTC by gagahpangeran

Closes #7782

Another solution to fix this:
- Create `u-plain-link` and use it for the thumbnail link, or
- Change `beatmap-discussion-timestamp__icons` to flex box, so the link box has same size with thumbnail image.

2021-10-05 13:36 UTC, nanaya requested changes

2021-10-05 13:36 UTC, nanaya commented on resources/views/beatmap_discussion_posts/_item.blade.php
> +                <a class="beatmap-discussion-timestamp__link-plain" href="{{ route('beatmapsets.discussion', $beatmapset) }}#/{{ $post->beatmap_discussion_id }}">
there's `link link--no-underline`

2021-10-05 14:33 UTC, gagahpangeran commented on resources/views/beatmap_discussion_posts/_item.blade.php
> +                <a class="beatmap-discussion-timestamp__link-plain" href="{{ route('beatmapsets.discussion', $beatmapset) }}#/{{ $post->beatmap_discussion_id }}">
Ah, that's what I need.

2021-10-06 07:16 UTC, nanaya approved these changes

2021-10-06 07:32 UTC, merged