Handle replay download with missing beatmap or user
ppy/osu-web pull request #8286
Opened 2021-11-02 10:11 UTC by nanaya

`headerChunk` throwing error is too late to abort once streamDownload runs.

2021-11-02 11:43 UTC, notbakaneko commented on app/Http/Controllers/ScoresController.php
> +            foreach ($file as $f) {
`foreach ($chunks as ...`? `foreach ($file` sounds weird

2021-11-02 12:22 UTC, nanaya commented
asset build fail on pr which doesn't even touch it is quite something :ok_hand:

2021-11-02 15:07 UTC, notbakaneko requested changes

2021-11-02 15:07 UTC, notbakaneko commented on app/Http/Controllers/ScoresController.php
> +        return response()->streamDownload(fn () => echo $file, $filename, ['Content-Type' => 'application/x-osu-replay']);
can't `fn () => echo ...`

besides, which are the params for `echo`, the closure and `streamDownload`

2021-11-04 08:00 UTC, notbakaneko approved these changes

2021-11-04 08:17 UTC, merged