Extra chat code cleanups
ppy/osu-web pull request #8349
Opened 2021-11-19 11:08 UTC by notbakaneko

- `nonPmChannels` is now `publicChannels` because that's what it is (and another grouping is coming)
- `channelList` moved to `ChatStateStore` because it's only used by that
- remove last usages of `inject`

2021-11-22 04:39 UTC, peppy commented on resources/assets/lib/stores/channel-store.ts
> +const visibleChannelTypes = new Set<ChannelType>(['PM', 'PUBLIC']);
I don't think we use it yet, but `GROUP` type should probably also be displayed.

2021-11-29 06:42 UTC, nanaya commented
Conflicts. And `publicChannels` now also includes `group` channels...? Maybe the previous `nonPmChannels` name is still better?

2021-12-02 05:05 UTC, nanaya commented
conflicts :eyes:

2021-12-02 05:17 UTC, notbakaneko commented
probably should make an alias for `Record<string, never>` at some point 👀

2021-12-02 10:30 UTC, nanaya requested changes

2021-12-07 12:16 UTC, nanaya approved these changes

2021-12-07 13:35 UTC, merged