Convert profile page to Typescript and use MobX state
ppy/osu-web pull request #8433
Opened 2021-12-10 12:33 UTC by nanaya

That's kinda big but basically all the state data are moved to the controller which gets passed around to all the components.

It's probably better to use state eventually but that involves creating a valid blank state. Also pretty much everything requires the controller anyway so nothing is purely just passing it.

Controller creation is in the Main because it's also handling the destruction which would be weird if the creation and destruction are separated?

- [ ] depends on #8421

2021-12-20 10:23 UTC, notbakaneko requested changes
part 1 of ?

2021-12-20 10:23 UTC, notbakaneko commented on resources/assets/lib/profile-page/historical.tsx
> +        updateTicks(chart);
`updateTicks` needs to run once with the right data before the chart is actually drawn (or chart redrawn after `updateTicks`).

2021-12-20 10:29 UTC, nanaya commented on resources/assets/lib/profile-page/main.tsx
> +                    <ExtraTab controller={this.controller} page={m} />
It's to prevent having Main component from observing `currentPage` so updates to that variable don't cause full rerender

2021-12-20 10:32 UTC, nanaya commented on resources/assets/lib/profile-page/controller.tsx
> +          pagination: this.state.pagination[section],
that's the best I could do without losing the typing

2021-12-20 11:08 UTC, notbakaneko commented on resources/assets/lib/profile-page/controller.tsx
> +          pagination: this.state.pagination[section],
```
derp<T extends ProfilePageSection>(section: T) {
  return {
    items: this.state.extras[section],
    pagination: this.state.pagination[section],
  };
}
```
?

2021-12-21 09:27 UTC, notbakaneko requested changes
Not really a new issue since it's already in the existing one, but reordering the tabs doesn't update the currently active section.

2021-12-21 11:01 UTC, notbakaneko approved these changes

2021-12-21 11:25 UTC, merged