replaced dash for unranked & loved maps with heart
ppy/osu-web pull request #8478
Opened 2022-01-04 19:17 UTC by DrOpossum

Implemented #8471 

The current solution displays a heart everywhere, not just for loved maps. I think this would be best as having dash, score or heart would be needlessly cluttered.

2022-01-04 20:01 UTC, Walavouchey commented
It wouldn't make sense to have a heart on a non-loved map

2022-01-04 20:31 UTC, DrOpossum commented
Alright, seems like that's what more people think. I'll adjust it accordingly then.

2022-01-06 09:52 UTC, nanaya requested changes
the code doesn't compile...

2022-01-13 07:14 UTC, nanaya approved these changes

2022-01-13 08:05 UTC, merged