Fix comment footer overlapping over "read more" button
ppy/osu-web pull request #8500
Opened 2022-01-11 05:43 UTC by notbakaneko

closes #8497

2022-01-11 05:48 UTC, notbakaneko commented
wonder if the button should be slighter larger for mobile, though 🤔

2022-01-11 06:29 UTC, nanaya commented
I'm not sure about fixing something that only happens in dev tool so I'm waiting for more details on where else it happens.

2022-01-11 07:12 UTC, nanaya requested changes
looks like it's better to add margin on the `read more` button instead with even more margin for mobile view

2022-01-19 07:51 UTC, nanaya requested changes

2022-01-19 07:51 UTC, nanaya commented on resources/assets/less/bem/comment.less
> +    gap: 2px;
should be 4px

2022-01-19 07:51 UTC, nanaya commented on resources/assets/less/bem/comment.less
> +      padding: 5px 0;
can use some margin for desktop as well as currently it's the only row with missing margin

2022-01-19 08:23 UTC, nanaya approved these changes

2022-01-19 08:23 UTC, merged