Remove unused cursor
ppy/osu-web pull request #8501
Opened 2022-01-11 12:21 UTC by nanaya

I can't find reference where the cursors are used 🤔 The controllers/bundles don't seem to accept `cursor` parameter either.

2022-01-11 13:02 UTC, notbakaneko commented
It's part of moving pagination, in particular for api responses, to using a cursor param. The bundle query should be updated to prioritize using a cursor, if anything.

2022-01-11 13:41 UTC, nanaya commented
Cursor support will need to be removed from html requests if anything other than offset pagination is going to be supported ಠ_ಠ The library probably shouldn't even be dealing with laravel offset paginator in the first place.

2022-02-02 08:43 UTC, notbakaneko requested changes

2022-02-02 08:43 UTC, notbakaneko commented on app/Http/Controllers/BeatmapDiscussionPostsController.php
> +     * cursor_string | string?                                                 | |
I think this should reference what `cursor_string` is for instead of just being `string?`

2022-02-02 10:39 UTC, notbakaneko approved these changes

2022-02-02 10:52 UTC, merged