Add participated multiplayer games to user profile page
ppy/osu-web pull request #8527
Opened 2022-01-19 15:34 UTC by notbakaneko

closes #7320

Old `multiplayer` is now `playlists` and `realtime` is `multiplayer`
...this naming is getting confusing 🤔 

I decided to split the lists into tabs instead of having them on the same tab at the last moment, as that seems to be more useful so I might be missing something 🤔 .

2022-01-20 07:31 UTC, peppy commented
Is "realtime" being shown to the user? Not sure we should be doing that if so.

2022-01-20 07:38 UTC, notbakaneko commented
`realtime` is in the url to match the existing category param naming; the display the for "realtime" says "multiplayer" instead

2022-01-20 07:40 UTC, notbakaneko commented
we can change the `realtime` param value to `multiplayer` if lazer updates to using `multiplayer` instead of `realtime` for the `category` param value

2022-01-20 08:12 UTC, peppy commented
If it's just in the URL I think it may be okay..

2022-01-21 14:04 UTC, nanaya commented
Category is either spotlight or normal. Previously it was normal/spotlight/realtime and then got moved out to type in #7965. Anything that still refer to "category" for those separation is just migration leftover and should be deleted/updated.

type is one of those playlists/head-to-head/team-versus. The grouping for playlists (just playlists) and realtime (head-to-head/team-versus) should then be type group or something.

2022-01-26 09:33 UTC, nanaya requested changes

2022-01-26 09:33 UTC, nanaya commented on app/Http/Controllers/Users/MultiplayerController.php
>          $user = FindForProfilePage::find($request->route('user'));
not really related but just noticed this can be just `$userId` if the function signature is `index($userId)`...

2022-01-26 09:33 UTC, nanaya commented on resources/lang/en/users.php
> +                'title' => 'Online Playlist Games',
where did the "Online" come from 🤔

2022-01-27 09:53 UTC, nanaya approved these changes

2022-01-27 10:10 UTC, merged