Restructure rooms listing
ppy/osu-web pull request #8635
Opened 2022-02-16 12:24 UTC by nanaya

Removes beatmap include and adds `difficulty_range.min` and `difficulty_range.max` 🤔 

...when `x-api-version: 20220215` is specified on the header.

2022-02-16 12:48 UTC, notbakaneko reviewed
The user playlist and multiplayer history pages could probably make use of `difficulty_range` too since all it uses the beatmaps for is the difficulty and cover image of the first one 🤔

2022-02-16 13:21 UTC, nanaya commented
Cover url is still needed for those pages so it's not as useful there (and more changes are needed).

2022-02-17 06:38 UTC, notbakaneko requested changes

2022-02-17 06:38 UTC, notbakaneko commented on app/Models/Multiplayer/Room.php
> +                $this->playlist->each(function ($item) use ($ret) {
`&$ret`

2022-02-17 07:49 UTC, notbakaneko approved these changes

2022-02-17 08:04 UTC, merged