More restructure room listing json
ppy/osu-web pull request #8642
Opened 2022-02-17 13:19 UTC by nanaya

Fun hacks™ inside.

Now I wonder if I can use it for `recent_participants` as well 🤔 

New JSON details can be checked [here](https://github.com/nanaya/osu-web/blob/e28389256d67d712c514df24215c2e95ce500792/resources/assets/lib/interfaces/room-json.ts). Following are included for `/rooms` endpoint:

- `current_playlist_item.beatmap.beatmapset`
- `difficulty_range`
- `host.country`
- `playlist_item_stats`
- `recent_participants`

2022-02-17 13:38 UTC, notbakaneko commented on app/Models/Multiplayer/Room.php
> +                $ret = $groupedItems[1]->reduce(fn (?PlaylistItem $ret, PlaylistItem $i) => $ret === null ? $i : ($i->playlist_order > $ret->playlist_order ? $i : $ret));
these lines look kind of long 👀

2022-02-18 06:06 UTC, smoogipoo requested changes

2022-02-18 06:36 UTC, nanaya commented on app/Models/Multiplayer/Room.php
> +                    return $i->playlist_order > $currentItem->playlist_order ? $i : $currentItem;
While at it, how should the playlist room be handled? (both playlist_order/played_at should be null, I assume?)

Should it always use first playlist item instead?

2022-02-18 06:37 UTC, peppy commented on app/Models/Multiplayer/Room.php
> +                    return $i->playlist_order > $currentItem->playlist_order ? $i : $currentItem;
I think that's adequate for now (always first item).

2022-02-18 07:18 UTC, notbakaneko requested changes

2022-02-18 07:18 UTC, notbakaneko commented on app/Models/Multiplayer/Room.php
> +    public function findAndSetCurrentPlaylistItem(): PlaylistItem
this will error if a `Room` has no playlist items (whose expected behaviour is currently being worked out 👀 )

2022-02-18 08:26 UTC, notbakaneko requested changes

2022-02-18 08:26 UTC, notbakaneko commented on resources/assets/lib/user-multiplayer-index/room.tsx
> +    const beatmapset = this.props.room.current_playlist_item.beatmap?.beatmapset;
not really an issue but this can return directly by continuing with `beatmapset?.covers.cover`

2022-02-21 10:16 UTC, peppy commented
Have tested to work well from our end 👍 .

2022-02-21 10:16 UTC, peppy approved these changes

2022-02-21 11:55 UTC, notbakaneko requested changes

2022-02-21 11:55 UTC, notbakaneko commented on app/Models/Multiplayer/Room.php
> +                        ? $groupedItems[0]->reduce(function (?PlaylistItem $currentItem, PlaylistItem $i) {
isn't the first param the carry and the second the current? 🤔

2022-02-21 12:38 UTC, notbakaneko approved these changes

2022-02-21 13:09 UTC, merged