Filter out blocked user's comments on beatmap pages.
ppy/osu-web pull request #8651
Opened 2022-02-20 04:13 UTC by jacobvm04

Fixes #8462 by filtering out comments written by users that are blocked by the logged in user when querying comments.

2022-02-21 05:43 UTC, notbakaneko requested changes
This doesn't do anything for replies.

We don't want to be being it this way, either; for query performance reasons and for how it breaks comment threads

2022-02-27 22:34 UTC, jacobvm04 commented
> This doesn't do anything for replies.
> 
> We don't want to be being it this way, either; for query performance reasons and for how it breaks comment threads

Ok, I've revised the PR to fit this criteria.

Now, comments from blocked users display
- In place of the message content, a message saying that the comment is not shown because it was from a blocked user.
- In place of the comment's author's name, "Blocked user".
- In place of the comment's author's avatar, the default avatar.
- An action button to display the comment anyway.

2022-03-03 06:07 UTC, notbakaneko requested changes
There's been some discussion about reducing the display to a smaller and simpler `This comment is hidden` type thing (still undecided), but at the very least the blocked comment should be dimmed like the deleted ones.

2022-03-03 15:27 UTC, jacobvm04 commented
> There's been some discussion about reducing the display to a smaller and simpler `This comment is hidden` type thing (still undecided), but at the very least the blocked comment should be dimmed like the deleted ones.

I've reduced the display message to your suggested one for now, the initial longer message was basically a placeholder and the suggested one sounds like a good replacement for now. 

Additionally, I've added dimming to the blocked comments like that of the deleted comments, and have set blocked comment's replies to be collapsed by default.

2022-03-11 08:23 UTC, notbakaneko requested changes
I mean something smaller like
![Screen Shot 2022-03-11 at 16 59 20](https://user-images.githubusercontent.com/1694544/157828583-d76ac2b9-ecd9-452f-af82-8a3aeff909aa.png)
; no icon, no username, no votes, just a single line.
Showing a blocked comment should remain dimmed, just like deleted comments

2022-03-11 08:23 UTC, notbakaneko commented on resources/assets/lib/components/comment.coffee
> +  toggleForceShow: =>
2 lines between methods for coffeescript

2022-03-11 08:23 UTC, notbakaneko commented on resources/assets/less/bem/comment.less
> +    &--blocked {
use and rename the existing `deleted` modifier instead.

2022-07-25 12:18 UTC, notbakaneko requested changes

2022-07-25 12:18 UTC, notbakaneko commented on resources/assets/lib/components/comment.coffee
> +            el 'p',
use `p` from react-dom-factories

2022-07-25 12:18 UTC, notbakaneko commented on resources/assets/lib/components/comment.coffee
> +          div className: 'comment__main blocked comment__message osu-md osu-md--comment',
`osu-md osu-md--comment` should be on the `p` element with `osu-md__paragraph`.
`comment__main blocked` shouldn't be here.

2022-07-25 12:18 UTC, notbakaneko commented on resources/assets/lib/components/comment.coffee
> +        return @renderBlocked()
The entire comment should be dimmed if the user is blocked, not just the placeholder.

2022-07-25 12:18 UTC, notbakaneko commented on resources/assets/lib/components/comment.coffee
> +  renderBlocked: =>
should take `mainClass` and `blockClass` param so the values from `render` can just be passed in.

2022-07-27 12:57 UTC, notbakaneko approved these changes

2022-07-27 13:09 UTC, merged