Add additional icons in recent events
ppy/osu-web pull request #8763
Opened 2022-04-02 15:22 UTC by KeziahMoselle

## Events

- [ ] beatmapPlaycount
- [x] beatmapsetApprove
- [x] beatmapsetDelete
- [ ] beatmapsetRevive
- [ ] beatmapsetUpdate
- [x] beatmapsetUpload
- [ ] rankLost
- [x] userSupportAgain
- [x] userSupportFirst
- [x] userSupportGift
- [x] usernameChange

### Colors

Should we color them as proposed initially? If so how?
With additionnal classes based on event type in `resources/assets/less/bem/page-extra.less` ?

closes #8410

2022-04-11 04:53 UTC, peppy commented
Are you able to provide a screenshot of how this looks so far?

2022-04-12 13:21 UTC, KeziahMoselle commented
Not yet, I need to seed the user profile with all possible types of events but I didn't see how yet

2022-04-13 05:55 UTC, nanaya commented
![](https://s.myconan.net/2022-04/firefox_2022-04-13_14-55-31.png)

2022-04-13 18:18 UTC, Loreos7 commented
Perhaps this down below would sute better "has been revived from eternal slumber"
![image](https://user-images.githubusercontent.com/86934170/163244159-6ee0c58b-1070-4ac7-a625-f293e0407bb8.png)
Although it could be smth like osu circle with the wings

And dont forget about the colors, because, at least, there are several statements for the beatmap: ranked, qualified, loved, approved

2022-04-13 18:36 UTC, KeziahMoselle commented
> Perhaps this down below would sute better for "has been revived from eternal slumber" ![image](https://user-images.githubusercontent.com/86934170/163244159-6ee0c58b-1070-4ac7-a625-f293e0407bb8.png) Although it could be smth like osu circle with the wings
> 
> And dont forget about the colors, because, at least, there are several statements for the beatmap: ranked, qualified, loved, approved

afaik the icon wave pulse isn't available in font awesome v5

2022-04-13 18:54 UTC, RockRoller01 commented
I believe a play icon for "map has been played x times" would be better, not to mention thats also what the play count medal uses

https://fontawesome.com/icons/play?s=solid

2022-04-13 20:09 UTC, KeziahMoselle commented on resources/assets/less/bem/profile-extra-entries.less
> +    }
I am unsure about this class organization 🤔

2022-04-13 20:10 UTC, KeziahMoselle commented
Here is a first version with colors: 
![image](https://user-images.githubusercontent.com/9168097/163262071-9a414784-cda9-4a5d-82c1-d36f428f0580.png)

2022-04-22 06:57 UTC, nanaya requested changes

2022-04-22 06:57 UTC, nanaya commented on resources/assets/lib/profile-page/parse-event.tsx
> +        badge: <span className='fas fa-sync-alt profile-extra-entries__icon--green' />,
```suggestion
        badge: <span className='fas fa-sync-alt profile-extra-entries__icon--green' />,
        iconModifiers: 'green',
```

And then adjust the render function to use the modifiers and apply it correctly to the `__icon` element.

2022-04-22 06:57 UTC, nanaya commented on resources/assets/less/bem/profile-extra-entries.less
> +      color: @green;
those `@$colour`s shouldn't be used anymore. Use `--hsl-$colour-$ver` instead.

2022-04-24 19:42 UTC, KeziahMoselle commented
Updated @nanaya 👍

2022-04-25 04:16 UTC, nanaya approved these changes

2022-04-25 04:31 UTC, merged