Add support for adding spotlight label to beatmaps
ppy/osu-web pull request #8768
Opened 2022-04-04 13:51 UTC by venix12

green one :eyes: (maybe pink would make more sense to match the spotlights marker in lazer?)

- needs to queue reindex when setting spotlight value, should there be an on-site UI for that perhaps?
- should run ``php artisan es:index-documents --types=beatmapsets --yes`` after merging

part of [#8736](https://github.com/ppy/osu-web/issues/8736)

2022-04-22 09:43 UTC, peppy commented
I think this should be fine to get merged in to see how it works?

@venix12 One question I have is whether the intention here is to mark any beatmap that was ever included in a spotlight, or whether to only mark active spotlight beatmaps?

2022-04-25 13:05 UTC, Ephemeralis commented
Marking any map ever featured in a spotlight has been the intention historically.

2022-04-25 13:06 UTC, venix12 commented
could also have them be a different colour or so for the active ones in the future (when the seasons system is in place, would just take playlist items of ongoing ones)

2022-04-26 02:55 UTC, nanaya requested changes

2022-04-26 02:55 UTC, nanaya commented on database/migrations/2022_04_04_152502_add_spotlight_to_osu_beatmapsets.php
> +<?php
update the date in filename

also the `osu_`/`Osu` prefix can be removed

(optionally change the class into anonymous class like in `2022_04_12_...` migration)

2022-04-26 02:55 UTC, nanaya commented on resources/assets/lib/components/beatmapset-panel.tsx
> +    {osu.trans(`beatmapsets.${type.replace('-', '_')}_badge.label`)}
`replaceAll` instead of `replace`

2022-05-11 04:06 UTC, nanaya requested changes

2022-05-11 10:03 UTC, nanaya commented
Conflicts 👀

2022-05-12 12:37 UTC, nanaya approved these changes
this involves adding a boolean column `spotlight` to `osu_beatmapsets`. It takes a bit on my system so if to be done manually, the migration entry will be `2022_04_30_152502_add_spotlight_to_beatmapsets`

2022-05-12 15:33 UTC, peppy approved these changes

2022-05-12 15:33 UTC, merged