Typescript beatmap header component
ppy/osu-web pull request #8829
Opened 2022-04-21 05:12 UTC by nanaya

More or less straight conversion after refactoring that favourite popup thing.

- [ ] #8827 
- [ ] #8802

2022-05-10 10:25 UTC, notbakaneko requested changes
It seems the page now renderers before going to verification after signing in instead of just going to verification 🤔

2022-05-10 10:25 UTC, notbakaneko commented on resources/assets/lib/beatmapsets-show/header.tsx
> +    if (core.userLogin.showIfGuest(this.onClickFavourite)) return;
does this even do anything if the button isn't even shown when guest?

2022-05-10 10:46 UTC, nanaya commented
looks like the rerender is a general existing bug of user data being set despite the page is getting a full reload (so the set is very much pointless).

2022-05-11 04:26 UTC, notbakaneko approved these changes

2022-05-11 04:52 UTC, merged