Update source for perfect score highlight
ppy/osu-web pull request #8878
Opened 2022-05-09 08:33 UTC by nanaya

Comparing `combo` attribute with beatmap's `max_combo` attribute seems to be the most correct method but there's currently nowhere to put it in the json. Even score's `beatmap.max_combo` in score display page could be wrong because that attribute ignores the score mods combination.

2022-05-09 08:56 UTC, peppy commented
Discussed this one IRL, but would appreciate a second check from @smoogipoo.

2022-05-10 04:56 UTC, smoogipoo requested changes

2022-05-10 04:56 UTC, smoogipoo commented on resources/assets/lib/utils/score-helper.ts
> +      'small_tick_miss',
Small ticks don't contribute to combo. Only miss + large ticks.

2022-05-10 05:14 UTC, smoogipoo submitted a review, later dismissed

2022-05-10 05:19 UTC, smoogipoo approved these changes

2022-05-10 06:30 UTC, notbakaneko approved these changes

2022-05-10 06:43 UTC, merged