Typescript beatmap main component
ppy/osu-web pull request #8894
Opened 2022-05-12 12:50 UTC by nanaya

States are now mobx and changes are done directly to the mobx state instead of having a listener.

- [ ] Depends on #8891

2022-05-18 11:54 UTC, notbakaneko requested changes
conflicts 💥

2022-05-24 11:45 UTC, notbakaneko requested changes

2022-05-24 11:46 UTC, nanaya commented on resources/assets/lib/beatmapsets-show/controller.tsx
> +      }
yes but can be turned into/from json easily

2022-05-24 12:52 UTC, nanaya commented on resources/assets/lib/beatmapsets-show/scoreboard.tsx
> +  controller: Controller;
Not sure if better 🤔 

The score resets on beatmap change but something still needs to hold the fetched data cache.

2022-06-06 08:45 UTC, notbakaneko approved these changes

2022-06-06 08:45 UTC, merged