Adjust spotlight badge colour
ppy/osu-web pull request #8957
Opened 2022-05-26 07:11 UTC by nanaya

Resolves #8924.

Also adjusted featured artist badge colour and unify hover styling.

2022-05-26 09:08 UTC, peppy approved these changes

2022-05-27 08:57 UTC, notbakaneko requested changes

2022-05-27 08:57 UTC, notbakaneko commented on resources/assets/less/bem/beatmapset-badge.less
> +  });
this doesn't seem to do anything (and apparently isn't working before the change, either?) 🤔

2022-05-27 11:18 UTC, notbakaneko approved these changes
hover thing was already broken, anyway 👀

2022-05-27 11:27 UTC, nanaya commented
it should work in beatmapset page. it's not linked in beatmapset panel so there's no hover effect there (pointer event is none iirc)

2022-05-27 11:49 UTC, merged