Allow disabling comment on specific item
ppy/osu-web pull request #8997
Opened 2022-06-08 08:22 UTC by nanaya

Resolves #8985 but only for admins with database access (or whatever other system) to actually disable commenting.

```sql
update osu_beatmapsets set comment_locked = 1 where beatmapset_id = $beatmapsetId;
```

This involves adding `comment_locked` column of type boolean/tinyint with default value of 0. Migration entry is

```
2022_06_08_065812_add_comment_locked_to_beatmapsets
```

in case manual migration is needed @peppy.

2022-06-08 10:00 UTC, peppy approved these changes

2022-06-08 11:58 UTC, notbakaneko requested changes
Replying to comment needs fixing, I think

2022-06-08 12:06 UTC, notbakaneko requested changes
Also comments are disabled when there are no comments yet 🤔

2022-06-08 13:30 UTC, notbakaneko approved these changes

2022-06-10 05:21 UTC, peppy commented
I've run the migration.

2022-06-10 05:21 UTC, peppy approved these changes

2022-06-10 06:56 UTC, merged