Improve chat channel unread marker handling
ppy/osu-web pull request #9006
Opened 2022-06-09 10:44 UTC by notbakaneko

Decouples the previous `markAsRead` from setting the unread marker position and uses the marker position when marking as read instead of assuming the last message.

There was an issue where when scrolling to the bottom of a channel and then scrolling back up and down again, if the scroll was not quite at the bottom of the channel when switching, it would not mark the channel as read.

should fix #9003

2022-07-06 09:19 UTC, notbakaneko commented
1. switch to channel with unread message
1. scroll to bottom
1. scroll up 1px
1. switch away -> channel still unread (should be considered read because got scrolled to bottom while window had focus)

cases where it shouldn't be considered read:
- window does not have focus
- did not scroll to bottom before switching away

2022-07-06 09:51 UTC, nanaya requested changes

2022-07-07 13:12 UTC, notbakaneko commented on resources/assets/lib/models/chat/channel.ts
> +      this.markAsReadLastSent = lastReadId;
not sure the delay is even needed, thinking about it again...

2022-07-08 07:42 UTC, nanaya approved these changes

2022-07-12 12:01 UTC, merged