Fix some mods being disallowed for playlist
ppy/osu-web pull request #9076
Opened 2022-07-01 17:35 UTC by nanaya

I completely forgot about it when actually writing the code 👀

2022-07-01 18:20 UTC, notbakaneko reviewed
should this handle the `UserPlayable` `false` cases?

2022-07-01 18:33 UTC, nanaya commented
Neither seem a breaking problem so maybe later. There's also configuration requirement which isn't checked at the moment either.

2022-07-01 18:38 UTC, notbakaneko commented
As far as I can tell, `ValidForMultiplayer: false` always has an associated `UserPlayable: false`, so non-realtime cases that were legitimately failing before would be passing now?

2022-07-01 18:41 UTC, nanaya commented
Anyone weird enough going through effort allowing cinema/autoplay mods probably already expect weird result in the first place.

2022-07-02 04:23 UTC, peppy commented
Let's deploy this early next week in case there's some new missed cases.

2022-07-05 12:35 UTC, notbakaneko requested changes

2022-07-05 12:35 UTC, notbakaneko commented on app/Libraries/Mods.php
> +    public function checkAllModsMeta(int $rulesetId, array $mods, callable $check, callable $failItemCallback): void
Everything in this function is external to the class other than the call to a `public $this->mods`, it looks like it should go in `PlaylistItem`

2022-07-06 13:51 UTC, merged