Add endpoint to fetch solo scores from elasticsearch
ppy/osu-web pull request #9110
Opened 2022-07-13 10:00 UTC by nanaya

Tests to be added and on production this depends on the scores to magically appear on elasticsearch 🪄

2022-07-15 08:44 UTC, peppy commented
Working flawlessly, although I have not checked the code. Would appreciate if this can be merged as a priority since I'll be wanting to keep it deployed (currently deployed from a temporary branch).

2022-07-15 08:45 UTC, peppy submitted a review, later dismissed

2022-07-15 11:08 UTC, notbakaneko requested changes
(still checking)

2022-07-15 11:08 UTC, notbakaneko commented on app/Libraries/Score/BeatmapScores.php
> +        if ($score === null && $totalScore === null) {
`$totalScore` from where 👀

2022-07-19 07:08 UTC, notbakaneko requested changes

2022-07-19 07:08 UTC, notbakaneko commented on app/Libraries/Score/UserRank.php
> +            return null;
I can't help but think this should throw instead of returning `null` if not set.

2022-07-19 07:08 UTC, notbakaneko commented on app/Libraries/Score/BeatmapScores.php
> +    public function rank(?SoloScore $score): ?int
Should this even be nullable? The only call currently does `isset` before calling

2022-07-19 10:19 UTC, notbakaneko approved these changes

2022-07-19 10:32 UTC, merged