🐛 Fix current email translation key in email update prompt
ppy/osu-web pull request #9209
Opened 2022-08-18 22:37 UTC by ThePooN

Presumably introduced by this PR https://github.com/ppy/osu-web/pull/1236 5 years ago... which I think tried fixing the wrong string. That's leaving me very confused o_O

2022-08-19 03:16 UTC, nanaya commented
Pretty sure that field is for current password 🤔 And if anything that translation entry should probably be deleted instead.

2022-08-19 04:23 UTC, notbakaneko requested changes
The field is for current password
![image](https://user-images.githubusercontent.com/1694544/185542314-b8f12c79-97ad-4a54-b45d-b0805c76aabe.png)

2022-08-19 11:35 UTC, ThePooN commented
Ah! got too easily convinced by that string presence.  
Updated the PR to remove it. I assume a crowdin update will remove it from all the lang files.

2022-08-25 06:49 UTC, nanaya approved these changes

2022-08-25 07:04 UTC, merged