Add auto skip to multiplayer rooms
ppy/osu-web pull request #9235
Opened 2022-08-31 11:27 UTC by smoogipoo

2022-08-31 12:18 UTC, peppy approved these changes

2022-08-31 13:01 UTC, nanaya requested changes

2022-08-31 13:01 UTC, nanaya commented on app/Models/Multiplayer/Room.php
> + * @property bool $auto_skip
also need to add the column to `$casts` variable (see [this](https://github.com/ppy/osu-web/blob/444721f0812540be670af1d580a7e2eada4421bf/app/Models/User.php#L192) for example)

2022-09-01 05:23 UTC, nanaya approved these changes

2022-09-01 05:42 UTC, merged