Add basic support for nominated beatmaps profile display
ppy/osu-web pull request #9444
Opened 2022-11-01 17:25 UTC by venix12

resolves #7555

Works with modding discussion system only for now... perhaps should scrap the nominations for older ones according to old forum icons system? Seems like a thing for different PR though.

Went with:
- ranked only
- only "final" (non-reset) nominations included

which is probably up to debate.

2022-11-01 17:30 UTC, Hiviexd commented
I think it makes sense to also include pending and qualified maps that are currently nominated by that user, they clearly fall under the category of "nominated maps".

2022-11-01 17:31 UTC, venix12 commented
Could be, went with ranked only as a placeholder pretty much.

2022-11-02 11:29 UTC, cl8n commented
> I think it makes sense to also include pending and qualified maps that are currently nominated by that user, they clearly fall under the category of "nominated maps".

since this is showing final nominations, I think it's fine as-is -- you don't know if the nominations are "final" until the map is ranked

2022-11-08 07:05 UTC, nanaya requested changes

2022-11-16 07:22 UTC, nanaya requested changes

2022-11-16 07:22 UTC, nanaya commented on database/migrations/2022_11_12_103015_index_user_id_on_beatmapset_nominations.php
> +            $table->index('user_id');
adding reset as well is probably good idea. Also the rollback should have the columns in an array

2022-11-16 14:11 UTC, merged