Update `UserGroupEvent` details format and log interface
ppy/osu-web pull request #9487
Opened 2022-11-09 07:01 UTC by cl8n

part 2
- [ ] depends on #9486 (not really but to avoid conflicts)

2022-12-02 10:21 UTC, nanaya requested changes

2022-12-02 10:45 UTC, nanaya requested changes

2022-12-02 10:45 UTC, nanaya commented on database/migrations/2022_11_06_022852_require_user_group_events_details_and_type.php
> +<?php
update migration file date

2022-12-02 20:12 UTC, cl8n commented on database/migrations/2022_11_06_022852_require_user_group_events_details_and_type.php
> +        UserGroupEvent::truncate();
true, should I change anything here to account for that? or just ask peppy to truncate again after deploy?

2023-01-05 13:44 UTC, nanaya approved these changes
@peppy please run the migration eventually. The exact timing shouldn't matter. It's just dropping existing data and adding null check to the columns which should already be always filled in.

2023-01-05 16:51 UTC, merged