Add group history endpoint
ppy/osu-web pull request #9488
Opened 2022-11-09 07:04 UTC by cl8n

part 3 ~

- [ ] depends on #9487

2023-08-04 11:57 UTC, nanaya requested changes

2023-08-04 11:57 UTC, nanaya commented on app/Transformers/UserGroupEventTransformer.php
> +            'name' => $event->details['actor_name'],
username?

2023-08-22 05:56 UTC, peppy commented
@cl8n wanna apply the reviews here to keep things moving? :)

2023-09-14 01:42 UTC, cl8n commented on app/Http/Controllers/GroupHistoryController.php
> +        }
renamed to min_date max_date , these names are used in beatmapset event search

2023-09-14 01:43 UTC, cl8n commented on app/Http/Controllers/GroupHistoryController.php
> +                $skipQuery = true;
scoped to none() the code was getting really messy lol

2023-09-20 04:31 UTC, peppy commented
@ppy/team-web can you check on this one? looks like it's ready for review.

2023-09-20 13:06 UTC, nanaya approved these changes

2023-09-20 13:17 UTC, merged