Use custom cast for store OrderItem extra_data
ppy/osu-web pull request #9607
Opened 2022-12-07 11:09 UTC by notbakaneko

Initial step for cleaning up some of the store logic and adding general improvements like #9578.
This adds custom casting for `extra_data` to have better structure instead of being a bag of fields just thrown in.
I've deliberately avoided changing the flow and most of the existing params handling or cleaning up the existing data - that will be done after #9578 is implemented.

2022-12-07 13:48 UTC, nanaya requested changes

2022-12-08 10:06 UTC, nanaya requested changes

2022-12-09 07:53 UTC, notbakaneko commented on app/Models/Store/Order.php
> +            'id:int',
It's used when removing items directly from the cart

2022-12-09 09:49 UTC, nanaya approved these changes

2022-12-09 11:45 UTC, merged