Use consistent order for FA tracks
ppy/osu-web pull request #9620
Opened 2022-12-10 02:12 UTC by cl8n

resolves #9519, and now display_order works outside of albums too if that's ever needed.

2023-01-25 09:11 UTC, nanaya requested changes

2023-01-25 09:11 UTC, nanaya commented on app/Http/Controllers/ArtistsController.php
> +                    ->orderBy('id', 'desc');
this part hasn't been working after the `tracks.artist` below was added. Also this one probably should have id ascending instead.

2023-09-20 04:34 UTC, peppy commented
Shall we un-stall this and get it merged?

2023-10-06 10:45 UTC, notbakaneko approved these changes

2023-10-06 11:01 UTC, merged

2023-10-06 19:25 UTC, cl8n commented
mb for missing this one, I'm not subscribed to this PRs notifications for some reason