Limit registration by ASN
ppy/osu-web pull request #9711
Opened 2023-01-04 13:25 UTC by nanaya

Alternative to #9697.

2023-01-04 15:24 UTC, ThePooN commented
Hmm, yeah I also have a few concerns about storing that database in the repo.

I would make geoip optional so we can run without the database in development (and remove it from git, ideally amending your existing commit to avoid bloating the repo).  
For deployments, I would add an env var pointing to the download location (eg. `https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=YOUR_LICENSE_KEY&suffix=tar.gz` or a local cache per MaxMind recommendations) for download at startup. Ideally optional too.

Don't think we really need a composer command for that, just bash scripts?

2023-01-05 07:04 UTC, notbakaneko requested changes
Given that the dbs are no longer downloadable without registering (https://blog.maxmind.com/2019/12/significant-changes-to-accessing-and-using-geolite2-databases/) we should probably look at the terms for including and using the database.

This looks like something that should download on `composer install`, but that's also adding another point of failure on deploys which I'm also not keen on 🤔

2023-01-05 09:23 UTC, nanaya commented
Fine, it's now using a free asn db provided by some dns person ಠ_ಠ

Initial lookup time increased by 1-2 second because the database is in text format and must be parsed. It could probably be sped up by caching it but 🤷‍♂️

2023-01-06 10:36 UTC, notbakaneko reviewed
The main issue I see is it takes ~~350mb~~(now) ~35mb on boot for every worker process 👀

2023-01-06 11:59 UTC, notbakaneko commented
Is it worth some basic sanity tests for `lookup`? 🤔

2023-01-06 13:11 UTC, notbakaneko approved these changes

2023-01-06 19:03 UTC, nanaya commented
So apparently just recording the row positions on the file could also work 👀 not sure about the performance though

2023-01-10 06:21 UTC, notbakaneko requested changes

2023-01-10 06:21 UTC, notbakaneko commented on app/Libraries/Ip2AsnUpdater.php
> +    private string $tsv;
unused

2023-01-10 06:21 UTC, notbakaneko commented on app/Libraries/Ip2AsnUpdater.php
> +        }
can do with newline maybe 🤔

2023-01-10 07:40 UTC, notbakaneko approved these changes

2023-01-10 07:40 UTC, merged