Add message length counter to create announcements UI
ppy/osu-web pull request #9752
Opened 2023-01-16 10:39 UTC by notbakaneko

recycled from existing `MessageLengthCounter`

#9741

2023-01-16 12:05 UTC, nanaya requested changes

2023-01-16 12:28 UTC, notbakaneko commented on resources/assets/lib/chat/create-announcement.tsx
> +            <MessageLengthCounter maxLength={this.model.maxLengths.name} message={this.model.inputs.name} />
Not sure if it's weird to have 2 counters at top and one at the bottom

2023-01-16 12:29 UTC, nanaya commented on resources/assets/lib/chat/create-announcement.tsx
> +            <MessageLengthCounter maxLength={this.model.maxLengths.name} message={this.model.inputs.name} />
also add label and move to the top maybe?

2023-01-16 12:44 UTC, notbakaneko commented on resources/assets/lib/chat/create-announcement.tsx
> +            <MessageLengthCounter maxLength={this.model.maxLengths.name} message={this.model.inputs.name} />
guess what's not in the design 👀 (the whole text box)

2023-01-17 08:53 UTC, nanaya commented on resources/assets/lib/chat/create-announcement.tsx
> +              id='chat-form-message'
`id` (and input container's `for`) not needed here? It was in `chat-form-users` just because it also contains buttons

2023-01-17 13:33 UTC, nanaya requested changes

2023-01-17 13:33 UTC, nanaya commented on resources/assets/lib/chat/create-announcement.tsx
> -                id='chat-form-users'
this one here is actually required because there are also buttons inside the label...

2023-01-18 06:41 UTC, nanaya approved these changes

2023-01-18 06:53 UTC, merged