Remove force-version flag when calling starting score indexer
ppy/osu-web pull request #9797
Opened 2023-01-26 15:01 UTC by notbakaneko

We're looking at remove the `--force-version` flag from the score indexer ppy/osu-elastic-indexer#137; github actions can just set the version with `run` before the tests.

This still has the issue for with docker compose where the score index isn't aliased after the docker containers start and has to be done separately (which is what `force-version` got around)

2023-01-27 07:03 UTC, nanaya requested changes
adding set schema command in docker dev prepare script is probably fine

2023-01-27 07:03 UTC, nanaya commented on .github/workflows/tests.yml
> +          php artisan es:index-scores:set-schema --schema=1
the actual schema version should be defined using env instead so it always matches docker compose

2023-05-23 05:53 UTC, peppy commented
@notbakaneko was this intended to address the issue mentioned in https://github.com/ppy/osu-elastic-indexer/pull/137#issuecomment-1404973857? If so can we revisit it? Would like to cross that PR off the list.

2023-05-23 13:07 UTC, notbakaneko commented
I remember running into an issue on the indexer side when testing the changes and didn't get further than that yet

2023-06-27 06:12 UTC, notbakaneko commented
`set-schema` needs to be after the indexer starts in order to alias any newly created index correctly

2023-06-27 06:42 UTC, nanaya commented
So what to do with dev env here?

2023-06-28 08:51 UTC, nanaya commented
is it just me or keeping `--force-version` would be way simpler?

2023-08-18 06:21 UTC, notbakaneko commented
All the additional stuff isn't needed
#10477

2023-08-18 06:21 UTC, closed without merging