Allow sorting forum topics by creation date
ppy/osu-web pull request #9903
Opened 2023-02-22 10:54 UTC by nanaya

As it turned out there's existing sort option already.

Resolves #9891, resolves #1705 (sort of). <sub>haha sort</sub>

2023-02-27 13:34 UTC, notbakaneko requested changes
should the index on production be created separately? 🤔

2023-02-27 14:47 UTC, nanaya commented
The table (`phpbb_topics`) isn't that big so I assume it should be fine. @peppy ?

2023-02-27 14:48 UTC, peppy commented
Should be fine.

2023-02-27 14:48 UTC, peppy approved these changes

2023-02-28 08:25 UTC, notbakaneko approved these changes

2023-02-28 08:40 UTC, merged