Add imagemap support to bbcode
ppy/osu-web pull request #9972
Opened 2023-03-09 13:27 UTC by nanaya

Syntax support for #8751. Frontend for it is missing.

I just hope enterprising user will create one if there's enough interest 👀

```
[imagemap]
imageurl
x y width height url1 optionaltitle
x y width height url2 optionaltitle
[/imagemap]
```

All the units (x, y, width, height) are in percent without the percent sign.

```
[imagemap]
https://assets.ppy.sh/osu-web-test-resources/placeholder-1280x720.jpg
0 0 50 50 https://google.com q1
0 50 50 50 https://yahoo.com q2
50 0 50 50 https://osu.ppy.sh q3
50 50 50 50 https://foobar2000.org q4
[/imagemap]
```

2023-03-09 13:45 UTC, RockRoller01 commented
Do I see it correctly that the URL is **not** optional? From my own experience with current imagemaps, making the url optional seems benefitial. For example in skinning we often only want some parts of the imagemap to be a link

2023-03-09 15:12 UTC, nanaya commented
image url isn't optional otherwise there's nothing to map to...

2023-03-09 15:44 UTC, RockRoller01 commented
ofc, my comment was solely focused on the areas you can define for an imagemap

2023-03-10 09:36 UTC, nanaya commented
Now I think again, I'm not sure if the positioning should use percent or pixel 🤔 if anyone have preference of one over the other please comment here.

2023-03-10 11:24 UTC, RockRoller01 commented
> if the positioning should use percent or pixel 

Looking at the code, wouldn't pixel result in a non-responsive design?

2023-03-10 11:30 UTC, nanaya commented
It'll be converted to percent

2023-04-04 14:25 UTC, notbakaneko requested changes

2023-04-04 14:25 UTC, notbakaneko commented on app/Libraries/BBCodeFromDB.php
> +                        $imageSize = fast_imagesize($imageUrl) ?? [0, 0];
I think there needs to be something better than rendering a 0x0 image if it fails to get the size, or just skip rendering the image. It's also not apparent to the user if something goes wrong here, they just get an image that gets displayed at 0px

2023-04-05 04:29 UTC, notbakaneko approved these changes

2023-04-05 04:44 UTC, merged